### ISSUE TITLE
oh-my-posh crash when special characters in the path

### ISSUE THREAD

**Issue by Cirn09** [JanDeDobbeleer/oh-my-posh#1033]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

`` D:\Work\a` ``: work well
`` D:\Work\a[] ``: work well
`` D:\Work\a[`] ``: crash

```
ResourceUnavailable: D:\Documents\PowerShell\Modules\oh-my-posh\5.7.2\oh-my-posh.psm1:77
Line |
  77 |      (& $poshCommand --init --shell=pwsh --config="$config") | Invoke- …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Program 'posh-windows-amd64.exe' failed to run: StandardOutputEncoding is only supported when standard
     | output is redirected.At D:\Documents\PowerShell\Modules\oh-my-posh\5.7.2\oh-my-posh.psm1:77 char:6 +
     | (& $poshCommand --init --shell=pwsh --config="$config") | Invoke- … +
     | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
```

### Version

5.7.2

### Theme

Paradox

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Relevant log output

```shell
ResourceUnavailable: D:\Documents\PowerShell\Modules\oh-my-posh\5.7.2\oh-my-posh.psm1:77
Line |
  77 |      (& $poshCommand --init --shell=pwsh --config="$config") | Invoke- …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Program 'posh-windows-amd64.exe' failed to run: StandardOutputEncoding is only supported when standard
     | output is redirected.At D:\Documents\PowerShell\Modules\oh-my-posh\5.7.2\oh-my-posh.psm1:77 char:6 +
     | (& $poshCommand --init --shell=pwsh --config="$config") | Invoke- … +
     | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.

PS D:\Work\a[`]> Get-Error

Type           : System.Management.Automation.CmdletInvocationException
ErrorRecord    :
    Exception             :
        Type        : System.Management.Automation.WildcardPatternException
        ErrorRecord :
            Exception             :
                Type    : System.Management.Automation.ParentContainsErrorRecordException
                Message : The specified wildcard character pattern is not valid: a\[`]
                HResult : -2146233087
            CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
            FullyQualifiedErrorId : RuntimeException
        TargetSite  :
            Name          : Parse
            DeclaringType : System.Management.Automation.WildcardPatternParser, System.Management.Automation, Version=7.1.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
            MemberType    : Method
            Module        : System.Management.Automation.dll
        StackTrace  :
   at System.Management.Automation.WildcardPatternParser.Parse(WildcardPattern pattern, WildcardPatternParser parser)
   at System.Management.Automation.WildcardPatternMatcher.MyWildcardPatternParser.Parse(WildcardPattern pattern, CharacterNormalizer characterNormalizer)
   at System.Management.Automation.WildcardPatternMatcher..ctor(WildcardPattern wildcardPattern)
   at System.Management.Automation.WildcardPattern.Init()
   at System.Management.Automation.LocationGlobber.IsChildNameAMatch(PSObject childObject, WildcardPattern stringMatcher, Collection`1 includeMatcher, Collection`1 excludeMatcher, String& childName)
   at System.Management.Automation.LocationGlobber.GenerateNewPSPathsWithGlobLeaf(List`1 currentDirs, PSDriveInfo drive, String leafElement, Boolean isLastLeaf, ContainerCmdletProvider provider, CmdletProviderContext context)
   at System.Management.Automation.LocationGlobber.ExpandMshGlobPath(String path, Boolean allowNonexistingPaths, PSDriveInfo drive, ContainerCmdletProvider provider, CmdletProviderContext context)
   at System.Management.Automation.LocationGlobber.ResolveDriveQualifiedPath(String path, CmdletProviderContext context, Boolean allowNonexistingPaths, CmdletProvider& providerInstance)
   at System.Management.Automation.LocationGlobber.GetGlobbedMonadPathsFromMonadPath(String path, Boolean allowNonexistingPaths, CmdletProviderContext context, CmdletProvider& providerInstance)
   at System.Management.Automation.PathIntrinsics.GetResolvedPSPathFromPSPath(String path, CmdletProviderContext context)
   at Microsoft.PowerShell.Commands.ResolvePathCommand.ProcessRecord()
   at System.Management.Automation.Cmdlet.DoProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
        Message     : The specified wildcard character pattern is not valid: a\[`]
        Source      : System.Management.Automation
        HResult     : -2146233087
    CategoryInfo          : NotSpecified: (:) [Resolve-Path], WildcardPatternException
    FullyQualifiedErrorId : RuntimeException,Microsoft.PowerShell.Commands.ResolvePathCommand
    InvocationInfo        :
        MyCommand       : Resolve-Path
        HistoryId       : 1
        InvocationName  : Microsoft.PowerShell.Management\Resolve-Path
        CommandOrigin   : Internal
    ScriptStackTrace      : at <ScriptBlock><End>, <No file>: line 38
                            at PSConsoleHostReadLine, C:\program files\powershell\7\Modules\PSReadLine\PSReadLine.psm1: line 4
    PipelineIterationInfo :



TargetSite     :
    Name          : Invoke
    DeclaringType : System.Management.Automation.Runspaces.PipelineBase, System.Management.Automation, Version=7.1.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
    MemberType    : Method
    Module        : System.Management.Automation.dll
StackTrace     :
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TOutput](IEnumerable input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   at System.Management.Automation.PowerShellExecutionHelper.ExecuteCurrentPowerShell(Exception& exceptionThrown, IEnumerable input)
Message        : The specified wildcard character pattern is not valid: a\[`]
InnerException :
    Type        : System.Management.Automation.WildcardPatternException
    ErrorRecord :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : The specified wildcard character pattern is not valid: a\[`]
            HResult : -2146233087
        CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : RuntimeException
    TargetSite  :
        Name          : Parse
        DeclaringType : System.Management.Automation.WildcardPatternParser, System.Management.Automation, Version=7.1.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    StackTrace  :
   at System.Management.Automation.WildcardPatternParser.Parse(WildcardPattern pattern, WildcardPatternParser parser)
   at System.Management.Automation.WildcardPatternMatcher.MyWildcardPatternParser.Parse(WildcardPattern pattern, CharacterNormalizer characterNormalizer)
   at System.Management.Automation.WildcardPatternMatcher..ctor(WildcardPattern wildcardPattern)
   at System.Management.Automation.WildcardPattern.Init()
   at System.Management.Automation.LocationGlobber.IsChildNameAMatch(PSObject childObject, WildcardPattern stringMatcher, Collection`1 includeMatcher, Collection`1 excludeMatcher, String& childName)
   at System.Management.Automation.LocationGlobber.GenerateNewPSPathsWithGlobLeaf(List`1 currentDirs, PSDriveInfo drive, String leafElement, Boolean isLastLeaf, ContainerCmdletProvider provider, CmdletProviderContext context)
   at System.Management.Automation.LocationGlobber.ExpandMshGlobPath(String path, Boolean allowNonexistingPaths, PSDriveInfo drive, ContainerCmdletProvider provider, CmdletProviderContext context)
   at System.Management.Automation.LocationGlobber.ResolveDriveQualifiedPath(String path, CmdletProviderContext context, Boolean allowNonexistingPaths, CmdletProvider& providerInstance)
   at System.Management.Automation.LocationGlobber.GetGlobbedMonadPathsFromMonadPath(String path, Boolean allowNonexistingPaths, CmdletProviderContext context, CmdletProvider& providerInstance)
   at System.Management.Automation.PathIntrinsics.GetResolvedPSPathFromPSPath(String path, CmdletProviderContext context)
   at Microsoft.PowerShell.Commands.ResolvePathCommand.ProcessRecord()
   at System.Management.Automation.Cmdlet.DoProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
    Message     : The specified wildcard character pattern is not valid: a\[`]
    Source      : System.Management.Automation
    HResult     : -2146233087
Source         : System.Management.Automation
HResult        : -2146233087


---

 Cirn09@LAPTOP-DDDDDD  D:  a['] 
❯ dir
Get-ChildItem: Cannot retrieve the dynamic parameters for the cmdlet. The specified wildcard character pattern is not valid: a\[`]
 Cirn09@LAPTOP-DDDDDD  D:  a[']  ERROR 
❯ Get-Error
as same as above.
```

**Comment by JanDeDobbeleer** [comment]
@Cirn09 the root cause is a Powershell issue as your path has an escape character in it. To be honest, my first reaction was "who does this?". I'll see of we can work around it, but I wouldn't be surprised this is a potential can of worms.

**Comment by JanDeDobbeleer** [comment]
@Cirn09 can you also open a ticket at Powershell? As it's their cmdlet that crashes and not oh-my-posh.

**Comment by Cirn09** [comment]
In fact, I also think "who does this?". I discovered this problem while experimenting with the `[` directory.

When starting directly with a special path, oh-my-posh will report an error, just like the error code posted above. And will not report an error when the `cd` special path. In any case, Powershell behaves very abnormally under a special path. This is what I just discovered. I will submit another issue to Powershell.

In addition, I am not very familiar with Powershell. I don't know what the ticket in Powershell is. But this problem is easy to reproduce, you can try it yourself.

**Comment by JanDeDobbeleer** [comment]
@Cirn09 you can't even navigate to the folder (even on macOS):
<img width="867" alt="image" src="https://user-images.githubusercontent.com/2492783/136705917-9a6a19e0-2feb-4bcf-af5a-732bf7ec13a7.png">

**Comment by JanDeDobbeleer** [comment]
I'm closing this as Powershell needs to fix it :-)

**Comment by Cirn09** [comment]
> @Cirn09 you can't even navigate to the folder (even on macOS): <img alt="image" width="867" src="https://user-images.githubusercontent.com/2492783/136705917-9a6a19e0-2feb-4bcf-af5a-732bf7ec13a7.png">

The correct command should be `` cd 'a`[```]' ``

**Comment by JanDeDobbeleer** [comment]
@Cirn09 it escaped this by itself based on path autocompletion 😵
