### ISSUE TITLE
First execution of oh-my-posh has rendering issues in WSL2

### ISSUE THREAD

**Issue by milkshakeuk** [JanDeDobbeleer/oh-my-posh#1388]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

The first time you launch WSL (ubuntu 18.04) the rendering of oh-my-posh is broken, but after that it renders fine.

![image](https://user-images.githubusercontent.com/1087376/145179276-fcfdb9f3-e310-4591-8793-2252baa5e828.png)

### Theme

janendobbeleer.omp.json

### What OS are you seeing the problem on?

Windows, Linux

### Which shell are you using?

bash

### Log output

```shell
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8d8e46]

goroutine 1 [running]:
main.(*AnsiWriter).isKeyword(...)
        /home/runner/work/oh-my-posh/oh-my-posh/src/writer_ansi.go:183
main.(*AnsiWriter).asAnsiColors(0x938c60, {0xc00002d50c, 0x9bc6ff}, {0xc00002d501, 0x0})
        /home/runner/work/oh-my-posh/oh-my-posh/src/writer_ansi.go:171 +0x2a6
main.(*AnsiWriter).write(0xc000246240, {0xc000219427, 0x7}, {0xc000219420, 0x8bccc5}, {0xc00002d500, 0x1e})
        /home/runner/work/oh-my-posh/oh-my-posh/src/writer_ansi.go:149 +0x2f5
main.(*Block).renderText(0xc00018e9a0, {0xc000243e78, 0x3})
        /home/runner/work/oh-my-posh/oh-my-posh/src/block.go:183 +0x196
main.(*Block).renderPlainSegment(...)
        /home/runner/work/oh-my-posh/oh-my-posh/src/block.go:170
main.(*Block).renderSegmentText(0xc00018e9a0, {0xc000243e78, 0x12fdca0})
        /home/runner/work/oh-my-posh/oh-my-posh/src/block.go:154 +0x49
main.(*Block).debug(0xc00018e9a0)
        /home/runner/work/oh-my-posh/oh-my-posh/src/block.go:211 +0x2b3
main.(*engine).debug(0xc0001c1df0)
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine.go:149 +0x5bf
main.main()
        /home/runner/work/oh-my-posh/oh-my-posh/src/main.go:233 +0x1025
```

**Comment by milkshakeuk** [comment]
@JanDeDobbeleer I still get the same issue with the latest version, here is the debug output:

![image](https://user-images.githubusercontent.com/1087376/145281228-bb0f80b1-2b09-40fb-9143-443eaa42a173.png)

```
Version: 6.28.1

Segments:

ConsoleTitle(true) -   1 ms - uni in JakeAitchison
session(true)  -   0 ms -  jake 
path(true)     -   0 ms -    JakeAitchison 
git(false)     - 116 ms -
dotnet(true)   - 114 ms -   6.0.100 
node(true)     - 122 ms -    
go(false)      -   5 ms -
julia(false)   -   4 ms -
python(false)  -  14 ms -
ruby(false)    -   7 ms -
azfunc(false)  -   1 ms -
aws(false)     -   0 ms -
root(false)    -   0 ms -
exit(true)     -   0 ms -  
shell(true)    -   0 ms -   uni 
ytm(false)     -   0 ms -
battery(true)  -   0 ms -   66 
time(true)     -   0 ms -  20:38:39 

Run duration: 391.544223ms

Logs:

2021/12/08 20:38:39 debug: getenv

2021/12/08 20:38:39 getenv duration: 7.419µs, args: XDG_CACHE_HOME
2021/12/08 20:38:39 getCachePath duration: 25.054µs, args:
2021/12/08 20:38:39 getArgs duration: 173ns, args:
2021/12/08 20:38:39 getArgs duration: 54ns, args:
2021/12/08 20:38:39 getShellName duration: 799ns, args:
2021/12/08 20:38:39 debug: getenv

2021/12/08 20:38:39 getenv duration: 2.711µs, args: OMP_CACHE_DISABLED
2021/12/08 20:38:39 isRunningAsRoot duration: 575ns, args:
2021/12/08 20:38:39 getcwd duration: 1.04251ms, args:
2021/12/08 20:38:39 getPathSeperator duration: 140ns, args:
2021/12/08 20:38:39 getPathSeperator duration: 92ns, args:
2021/12/08 20:38:39 getPathSeperator duration: 92ns, args:
2021/12/08 20:38:39 getPathSeperator duration: 89ns, args:
2021/12/08 20:38:39 getPathSeperator duration: 85ns, args:
2021/12/08 20:38:39 getPathSeperator duration: 80ns, args:
2021/12/08 20:38:39 getPathSeperator duration: 74ns, args:
2021/12/08 20:38:39 getPathSeperator duration: 79ns, args:
2021/12/08 20:38:39 getPathSeperator duration: 102ns, args:
2021/12/08 20:38:39 getPathSeperator duration: 82ns, args:
2021/12/08 20:38:39 getPathSeperator duration: 68ns, args:
2021/12/08 20:38:39 getPathSeperator duration: 93ns, args:
2021/12/08 20:38:39 getPathSeperator duration: 92ns, args:
2021/12/08 20:38:39 getPathSeperator duration: 99ns, args:
2021/12/08 20:38:39 getPathSeperator duration: 117ns, args:
2021/12/08 20:38:39 getShellName duration: 218ns, args:
2021/12/08 20:38:39 getCurrentUser duration: 1.012µs, args:
2021/12/08 20:38:39 getHostName duration: 3.788µs, args:
2021/12/08 20:38:39 getcwd duration: 267ns, args:
2021/12/08 20:38:39 debug: getenv

2021/12/08 20:38:39 getenv duration: 2.393µs, args: SSH_CONNECTION
2021/12/08 20:38:39 debug: getenv

2021/12/08 20:38:39 getenv duration: 2.063µs, args: SSH_CLIENT
2021/12/08 20:38:39 getCurrentUser duration: 265ns, args:
2021/12/08 20:38:39 getRuntimeGOOS duration: 77ns, args:
2021/12/08 20:38:39 getHostName duration: 1.517µs, args:
2021/12/08 20:38:39 isRunningAsRoot duration: 379ns, args:
2021/12/08 20:38:39 getcwd duration: 172ns, args:
2021/12/08 20:38:39 getcwd duration: 62ns, args:
2021/12/08 20:38:39 getArgs duration: 101ns, args:
2021/12/08 20:38:39 getcwd duration: 65ns, args:
2021/12/08 20:38:39 getRuntimeGOOS duration: 89ns, args:
2021/12/08 20:38:39 getRuntimeGOOS duration: 49ns, args:
2021/12/08 20:38:39 getPathSeperator duration: 87ns, args:
2021/12/08 20:38:39 getPathSeperator duration: 60ns, args:
2021/12/08 20:38:39 getPathSeperator duration: 70ns, args:
2021/12/08 20:38:39 getPathSeperator duration: 60ns, args:
2021/12/08 20:38:39 getPathSeperator duration: 51ns, args:
2021/12/08 20:38:39 getPathSeperator duration: 57ns, args:
2021/12/08 20:38:39 getPathSeperator duration: 49ns, args:
2021/12/08 20:38:39 getPathSeperator duration: 49ns, args:
2021/12/08 20:38:39 getPathSeperator duration: 62ns, args:
2021/12/08 20:38:39 getPathSeperator duration: 55ns, args:
2021/12/08 20:38:39 getPathSeperator duration: 48ns, args:
2021/12/08 20:38:39 getPathSeperator duration: 57ns, args:
2021/12/08 20:38:39 getPathSeperator duration: 49ns, args:
2021/12/08 20:38:39 getPathSeperator duration: 51ns, args:
2021/12/08 20:38:39 getPathSeperator duration: 55ns, args:
2021/12/08 20:38:39 getPathSeperator duration: 58ns, args:
2021/12/08 20:38:39 getRuntimeGOOS duration: 70ns, args:
2021/12/08 20:38:39 getcwd duration: 52ns, args:
2021/12/08 20:38:39 getRuntimeGOOS duration: 65ns, args:
2021/12/08 20:38:39 debug: getenv
Ubuntu-18.04
2021/12/08 20:38:39 getenv duration: 2.146µs, args: WSL_DISTRO_NAME
2021/12/08 20:38:39 isWsl duration: 12.925µs, args:
2021/12/08 20:38:39 getcwd duration: 54ns, args:
2021/12/08 20:38:39 debug: runCommand
5.10.60.1-microsoft-standard-WSL2
2021/12/08 20:38:39 runCommand duration: 1.134833ms, args: uname -r
2021/12/08 20:38:39 hasCommand duration: 113.170051ms, args: git.exe
2021/12/08 20:38:39 getcwd duration: 306ns, args:
2021/12/08 20:38:39 error: hasParentFilePath
stat /.git: no such file or directory
2021/12/08 20:38:39 hasParentFilePath duration: 2.074321ms, args: .git
2021/12/08 20:38:39 getcwd duration: 176ns, args:
2021/12/08 20:38:39 getcwd duration: 47ns, args:
2021/12/08 20:38:39 hasCommand duration: 20.495µs, args: dotnet
2021/12/08 20:38:39 debug: runCommand
6.0.100
2021/12/08 20:38:39 runCommand duration: 114.474868ms, args: dotnet --version
2021/12/08 20:38:39 getcwd duration: 129ns, args:
2021/12/08 20:38:39 getcwd duration: 32ns, args:
2021/12/08 20:38:39 getcwd duration: 35ns, args:
2021/12/08 20:38:39 getPathSeperator duration: 52ns, args:
2021/12/08 20:38:39 hasFiles duration: 3.005197ms, args: *.js
2021/12/08 20:38:39 error: hasCommand
exec: "node": executable file not found in $PATH
2021/12/08 20:38:39 hasCommand duration: 119.956781ms, args: node
2021/12/08 20:38:39 getcwd duration: 308ns, args:
2021/12/08 20:38:39 getcwd duration: 106ns, args:
2021/12/08 20:38:39 getcwd duration: 64ns, args:
2021/12/08 20:38:39 getPathSeperator duration: 123ns, args:
2021/12/08 20:38:39 hasFiles duration: 4.917689ms, args: *.go
2021/12/08 20:38:39 getcwd duration: 275ns, args:
2021/12/08 20:38:39 getPathSeperator duration: 93ns, args:
2021/12/08 20:38:39 hasFiles duration: 370.726µs, args: go.mod
2021/12/08 20:38:39 getcwd duration: 149ns, args:
2021/12/08 20:38:39 getcwd duration: 74ns, args:
2021/12/08 20:38:39 getcwd duration: 65ns, args:
2021/12/08 20:38:39 getPathSeperator duration: 79ns, args:
2021/12/08 20:38:39 hasFiles duration: 4.022927ms, args: *.jl
2021/12/08 20:38:39 getcwd duration: 89ns, args:
2021/12/08 20:38:39 getcwd duration: 32ns, args:
2021/12/08 20:38:39 getcwd duration: 36ns, args:
2021/12/08 20:38:39 getPathSeperator duration: 65ns, args:
2021/12/08 20:38:39 hasFiles duration: 5.139098ms, args: *.py
2021/12/08 20:38:39 getcwd duration: 60ns, args:
2021/12/08 20:38:39 getPathSeperator duration: 50ns, args:
2021/12/08 20:38:39 hasFiles duration: 6.217817ms, args: *.ipynb
2021/12/08 20:38:39 getcwd duration: 99ns, args:
2021/12/08 20:38:39 getPathSeperator duration: 60ns, args:
2021/12/08 20:38:39 hasFiles duration: 801.238µs, args: pyproject.toml
2021/12/08 20:38:39 getcwd duration: 58ns, args:
2021/12/08 20:38:39 getPathSeperator duration: 39ns, args:
2021/12/08 20:38:39 hasFiles duration: 772.933µs, args: venv.bak
2021/12/08 20:38:39 getcwd duration: 79ns, args:
2021/12/08 20:38:39 getPathSeperator duration: 56ns, args:
2021/12/08 20:38:39 hasFiles duration: 554.978µs, args: venv
2021/12/08 20:38:39 getcwd duration: 74ns, args:
2021/12/08 20:38:39 getPathSeperator duration: 62ns, args:
2021/12/08 20:38:39 hasFiles duration: 974.554µs, args: .venv
2021/12/08 20:38:39 getcwd duration: 58ns, args:
2021/12/08 20:38:39 getcwd duration: 28ns, args:
2021/12/08 20:38:39 getcwd duration: 29ns, args:
2021/12/08 20:38:39 getPathSeperator duration: 42ns, args:
2021/12/08 20:38:39 hasFiles duration: 6.836191ms, args: *.rb
2021/12/08 20:38:39 getcwd duration: 109ns, args:
2021/12/08 20:38:39 getPathSeperator duration: 83ns, args:
2021/12/08 20:38:39 hasFiles duration: 537.917µs, args: Rakefile
2021/12/08 20:38:39 getcwd duration: 112ns, args:
2021/12/08 20:38:39 getPathSeperator duration: 71ns, args:
2021/12/08 20:38:39 hasFiles duration: 572.247µs, args: Gemfile
2021/12/08 20:38:39 getcwd duration: 163ns, args:
2021/12/08 20:38:39 getcwd duration: 50ns, args:
2021/12/08 20:38:39 getcwd duration: 52ns, args:
2021/12/08 20:38:39 getPathSeperator duration: 77ns, args:
2021/12/08 20:38:39 hasFiles duration: 295.422µs, args: host.json
2021/12/08 20:38:39 getcwd duration: 115ns, args:
2021/12/08 20:38:39 getPathSeperator duration: 72ns, args:
2021/12/08 20:38:39 hasFiles duration: 263.375µs, args: local.settings.json
2021/12/08 20:38:39 getcwd duration: 73ns, args:
2021/12/08 20:38:39 getPathSeperator duration: 64ns, args:
2021/12/08 20:38:39 hasFiles duration: 498.655µs, args: function.json
2021/12/08 20:38:39 getcwd duration: 83ns, args:
2021/12/08 20:38:39 debug: getenv

2021/12/08 20:38:39 getenv duration: 2.148µs, args: AWS_VAULT
2021/12/08 20:38:39 debug: getenv

2021/12/08 20:38:39 getenv duration: 915ns, args: AWS_PROFILE
2021/12/08 20:38:39 debug: getenv

2021/12/08 20:38:39 getenv duration: 702ns, args: AWS_REGION
2021/12/08 20:38:39 debug: getenv

2021/12/08 20:38:39 getenv duration: 799ns, args: AWS_DEFAULT_REGION
2021/12/08 20:38:39 debug: getenv

2021/12/08 20:38:39 getenv duration: 3.709µs, args: AWS_CONFIG_FILE
2021/12/08 20:38:39 error: getFileContent
open /home/jake/.aws/config: no such file or directory
2021/12/08 20:38:39 getFileContent duration: 6.849µs, args: /home/jake/.aws/config
2021/12/08 20:38:39 getcwd duration: 69ns, args:
2021/12/08 20:38:39 isRunningAsRoot duration: 504ns, args:
2021/12/08 20:38:39 getcwd duration: 48ns, args:
2021/12/08 20:38:39 lastErrorCode duration: 353ns, args:
2021/12/08 20:38:39 getcwd duration: 167ns, args:
2021/12/08 20:38:39 getShellName duration: 312ns, args:
2021/12/08 20:38:39 getcwd duration: 95ns, args:
2021/12/08 20:38:39 error: doGet
Get "http://127.0.0.1:9863/query": dial tcp 127.0.0.1:9863: connect: connection refused
2021/12/08 20:38:39 doGet duration: 305.707µs, args: http://127.0.0.1:9863/query
2021/12/08 20:38:39 getcwd duration: 136ns, args:
2021/12/08 20:38:39 getBatteryInfo duration: 565.507µs, args:
2021/12/08 20:38:39 getcwd duration: 171ns, args:
```

**Comment by JanDeDobbeleer** [comment]
Can you share the exact config?

**Comment by JanDeDobbeleer** [comment]
@milkshakeuk wait, I fixed the error in the log you reported, BUT the issue you're referring to is a [Windows Terminal](https://ohmyposh.dev/docs/faq#windows-terminal-unexpected-space-between-segmentstext) issue. The fix is in the link.

**Comment by milkshakeuk** [comment]
@JanDeDobbeleer it might be a bug in windows terminal but it works fine with gitbash? are you sure its Windows Terminal in this case?

![oh-my-posh](https://user-images.githubusercontent.com/1087376/145364804-0dc43071-33e5-419c-9653-a3cfcf9f0a79.gif)

**Comment by JanDeDobbeleer** [comment]
@milkshakeuk it only happens on PowerShell inside Windows Terminal 😄

**Comment by milkshakeuk** [comment]
@JanDeDobbeleer and WSL it seems?

**Comment by JanDeDobbeleer** [comment]
@milkshakeuk apparently, the FAQ items also contains the link to the WT issue.
