### ISSUE TITLE
Git segment gets a runtime error with version 6.28.0

### ISSUE THREAD

**Issue by MJECloud** [JanDeDobbeleer/oh-my-posh#1391]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

With version 6.28.0 the git segment gets a runtime error. 

![image](https://user-images.githubusercontent.com/22131101/145236463-ed56c3f6-7c5a-40b6-9905-ba9502ba3a69.png)

### Theme

```json
{
    "$schema": "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json",
    "final_space": false,
    "console_title": true,
    "console_title_style": "template",
    "console_title_template": "{{if .Root}} \u2728 {{end}} {{ .Folder }}",
    "blocks": [
        {
            "type": "prompt",
            "alignment": "left",
            "segments": [
                {
                    "type": "root",
                    "style": "powerline",
                    "foreground": "#ffffff",
                    "properties": {
                        "root_icon": "\u2728",
                        "prefix": ""
                    }
                },
                {
                    "type": "envvar",
                    "foreground": "#89008f",
                    "style": "powerline",
                    "properties": {
                        "var_name": "oh_my_userName",
                        "postfix": "@",
                        "prefix": ""
                    }
                },
                {
                    "type": "os",
                    "style": "powerline",
                    "foreground": "#0099a1",
                    "properties": {
                        "postfix": " ",
                        "prefix": ""
                    }
                },
                {
                    "type": "text",
                    "style": "powerline",
                    "foreground": "#ffffff",
                    "properties": {
                        "text": "|",
                        "prefix": "",
                        "postfix": ""
                    }
                },
                {
                    "type": "path",
                    "style": "powerline",
                    "foreground": "#0077c2",
                    "properties": {
                        "prefix": "  ",
                        "style": "folder",
                        "enable_hyperlink": true,
                        "postfix": " "
                    }
                },
                {
                    "type": "git",
                    "style": "powerline",
                    "powerline_symbol": "",
                    "foreground": "#0bde32",
                    "properties": {
                        "color_background": false,
                        "display_stash_count": true,
                        "display_upstream_icon": true,
                        "display_status": true,
                        "status_colors_enabled": true,
                        "behind_color": "#ed070b",
                        "local_changes_color": "#d6d333",
                        "ahead_color": "#ff79c6",
                        "ahead_and_behind_color": "#db5727",
                        "prefix": "{ ",
                        "postfix": " }"
                    }
                }
            ]
        },
        {
            "type": "prompt",
            "alignment": "right",
            "segments": [
                {
                    "type": "envvar",
                    "style": "diamond",
                    "foreground": "#00FF00",
                    "properties": {
                        "var_name": "oh_my_success"
                    }
                },
                {
                    "type": "envvar",
                    "style": "diamond",
                    "foreground": "#FF0000",
                    "properties": {
                        "var_name": "oh_my_failure"
                    }
                },
                {
                    "type": "envvar",
                    "style": "powerline",
                    "foreground": "#546E7A",
                    "properties": {
                        "prefix": "[ ",
                        "var_name": "oh_my_executionTime",
                        "postfix": " ]"
                    }
                },
                {
                    "type": "time",
                    "style": "powerline",
                    "foreground": "#bb6868",
                    "properties": {
                        "time_format": "15:04:05",
                        "postfix": " \uF017"
                    }
                }
            ]
        },
        {
            "type": "prompt",
            "alignment": "left",
            "newline": true,
            "segments": [
                {
                    "type": "exit",
                    "style": "plain",
                    "properties": {
                        "prefix": "<#007ACC>~</><#43D426>@</><#FF0000>❯</>",
                        "always_enabled": true,
                        "display_exit_code": false
                    }
                }
            ]
        }
    ]
}
```

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```shell
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0xaa6c41]

goroutine 1 [running]:
main.(*GitStatus).Changed(...)
        /home/runner/work/oh-my-posh/oh-my-posh/src/segment_git.go:35
main.(*git).getStatusColor(0xb71f20, {0x0, 0xbab0b1})
        /home/runner/work/oh-my-posh/oh-my-posh/src/segment_deprecated.go:119 +0x21
main.(*git).SetStatusColor(0xc0002424b0)
        /home/runner/work/oh-my-posh/oh-my-posh/src/segment_deprecated.go:114 +0x95
main.(*git).deprecatedString(0xc0002424b0, 0x80)
        /home/runner/work/oh-my-posh/oh-my-posh/src/segment_deprecated.go:78 +0x29
main.(*git).string(0xc0002424b0)
        /home/runner/work/oh-my-posh/oh-my-posh/src/segment_git.go:206 +0x2b1
main.(*Segment).string(...)
        /home/runner/work/oh-my-posh/oh-my-posh/src/segment.go:141
main.(*Block).debug(0xc000158370)
        /home/runner/work/oh-my-posh/oh-my-posh/src/block.go:207 +0x203
main.(*engine).debug(0xc000115df0)
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine.go:149 +0x5bf
main.main()
        /home/runner/work/oh-my-posh/oh-my-posh/src/main.go:233 +0x1025

oh-my-posh fatal error rendering git segment:runtime error: invalid memory address or nil pointer dereference

goroutine 11 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.17.3/x64/src/runtime/debug/stack.go:24 +0x65
main.(*Segment).setStringValue.func1()
        /home/runner/work/oh-my-posh/oh-my-posh/src/segment.go:287 +0x58
panic({0xb23cc0, 0x14f00b0})
        /opt/hostedtoolcache/go/1.17.3/x64/src/runtime/panic.go:1038 +0x215
main.(*GitStatus).Changed(...)
        /home/runner/work/oh-my-posh/oh-my-posh/src/segment_git.go:35
main.(*git).getStatusColor(0xb71f20, {0x0, 0xbab0b1})
        /home/runner/work/oh-my-posh/oh-my-posh/src/segment_deprecated.go:119 +0x21
main.(*git).SetStatusColor(0xc000230000)
        /home/runner/work/oh-my-posh/oh-my-posh/src/segment_deprecated.go:114 +0x95
main.(*git).deprecatedString(0xc000230000, 0x80)
        /home/runner/work/oh-my-posh/oh-my-posh/src/segment_deprecated.go:78 +0x29
main.(*git).string(0xc000230000)
        /home/runner/work/oh-my-posh/oh-my-posh/src/segment_git.go:206 +0x2b1
main.(*Segment).string(...)
        /home/runner/work/oh-my-posh/oh-my-posh/src/segment.go:141
main.(*Segment).setStringValue(0xc0001c0f00, {0xc88500, 0xc000062b90})
        /home/runner/work/oh-my-posh/oh-my-posh/src/segment.go:297 +0xc5
main.(*Block).setStringValues.func1(0x0)
        /home/runner/work/oh-my-posh/oh-my-posh/src/block.go:87 +0x65
created by main.(*Block).setStringValues
        /home/runner/work/oh-my-posh/oh-my-posh/src/block.go:85 +0x9d
```

**Comment by JanDeDobbeleer** [comment]
@MJECloud please downgrade as I can't push a fix due GH having issues ATM. The fix is ready and I removed this version from the lists.

**Comment by MJECloud** [comment]
Alright, thanks for the info! I'll downgrade. 😊

**Comment by JanDeDobbeleer** [comment]
6.28.1 is pushed, should be there soon

**Comment by MJECloud** [comment]
Thanks, works like a charm!
