### ISSUE TITLE
Powershell: fatal error rendering kubectl

### ISSUE THREAD

**Issue by jandhollander** [JanDeDobbeleer/oh-my-posh#1439]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Using certain themes in Powershell (I suppose the ones that display a kubectl segment), an error pops up and part of the shell displays 'error'.

I would expect no error.

![image](https://user-images.githubusercontent.com/2222862/146216999-a1eb1d4e-fe19-4d6b-b7b5-0824ca59bf9d.png)

### Theme

config in my profile: oh-my-posh --init --shell pwsh --config ~\AppData\Local\Programs\oh-my-posh\themes\atomic.omp.json | Invoke-Expression

themes: atomic, night-owl

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```shell
panic: runtime error: index out of range [2] with length 2
System.Management.Automation.RemoteException
goroutine 1 [running]:
main.(*kubectl).doCallKubectl(0xc00009d680)
        /home/runner/work/oh-my-posh/oh-my-posh/src/segment_kubectl.go:126 +0x33d
main.(*kubectl).enabled(0xc00009d680)
        /home/runner/work/oh-my-posh/oh-my-posh/src/segment_kubectl.go:58 +0x79
main.(*Segment).enabled(...)
        /home/runner/work/oh-my-posh/oh-my-posh/src/segment.go:145
main.(*Block).debug(0xc0001646e0)
        /home/runner/work/oh-my-posh/oh-my-posh/src/block.go:202 +0x187
main.(*engine).debug(0xc00011bdf0)
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine.go:149 +0x5bf
main.main()
        /home/runner/work/oh-my-posh/oh-my-posh/src/main.go:233 +0x1025

oh-my-posh fatal error rendering kubectl segment:runtime error: index out of range [2] with length 2

goroutine 35 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.17.3/x64/src/runtime/debug/stack.go:24 +0x65
main.(*Segment).setStringValue.func1()
        /home/runner/work/oh-my-posh/oh-my-posh/src/segment.go:284 +0x58
panic({0x7ea900, 0xc0003a8738})
        /opt/hostedtoolcache/go/1.17.3/x64/src/runtime/panic.go:1038 +0x215
main.(*kubectl).doCallKubectl(0xc0004860c0)
        /home/runner/work/oh-my-posh/oh-my-posh/src/segment_kubectl.go:126 +0x33d
main.(*kubectl).enabled(0xc0004860c0)
        /home/runner/work/oh-my-posh/oh-my-posh/src/segment_kubectl.go:58 +0x79
main.(*Segment).enabled(...)
        /home/runner/work/oh-my-posh/oh-my-posh/src/segment.go:145
main.(*Segment).setStringValue(0xc000246900, {0x905f40, 0xc00006ab90})
        /home/runner/work/oh-my-posh/oh-my-posh/src/segment.go:293 +0xa2
main.(*Block).setStringValues.func1(0x0)
        /home/runner/work/oh-my-posh/oh-my-posh/src/block.go:87 +0x65
created by main.(*Block).setStringValues
        /home/runner/work/oh-my-posh/oh-my-posh/src/block.go:85 +0x9d
```

**Comment by JanDeDobbeleer** [comment]
@jandhollander can you also show the output of `Write-PoshDebug` in the folder where it happens? As I can then see the exact output (I added the safeguard now, will push that already).

**Comment by jandhollander** [comment]
@JanDeDobbeleer the output from Write-PoshDebug is posted in the 'Log Output' section of the issue description.
Thanks for picking this up so quickly.

**Comment by JanDeDobbeleer** [comment]
@jandhollander I do miss the output of the kubectl command to understand what it's trying to parse (I don't have that enabled here). What's the output of the following command:

```bash
kubectl config view --minify --output jsonpath={..current-context},{..namespace},{..context.user},{..context.cluster}
```

**Comment by jandhollander** [comment]
I get
```
error: unexpected arguments: [..current-context,..namespace,..context.user,..context.cluster]
See 'kubectl config view -h' for help and examples
```

If I just run `kubectl config view --minify` I get:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://127.0.0.1:59825
  name: kind-kind
contexts:
- context:
    cluster: kind-kind
    user: kind-kind
  name: kind-kind
current-context: kind-kind
kind: Config
preferences: {}
users:
- name: kind-kind
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
```

**Comment by JanDeDobbeleer** [comment]
@JanDeDobbeleer what if you update kubectl?

**Comment by jandhollander** [comment]
@JanDeDobbeleer (tagging someone with the same 4 first letters is confusing :p) 
I was on kubectl v1.22 (released in august 2021) but indeed, the upgrade to v1.23 did the trick.

Thanks for your help.

Do you think showing a clearer error message would be possible? Or a version check if a particular version of a tool is required? (just thinking on how this experience could improve)

**Comment by JanDeDobbeleer** [comment]
@jandhollander can you give me the output of `kubectl config view --minify --output json`? That way we can parse the object rather than rely on an index.

**Comment by jandhollander** [comment]
@JanDeDobbeleer 
This is what I get:

```
{
    "kind": "Config",
    "apiVersion": "v1",
    "preferences": {},
    "clusters": [
        {
            "name": "kind-kind",
            "cluster": {
                "server": "https://127.0.0.1:59825",
                "certificate-authority-data": "DATA+OMITTED"
            }
        }
    ],
    "users": [
        {
            "name": "kind-kind",
            "user": {
                "client-certificate-data": "REDACTED",
                "client-key-data": "REDACTED"
            }
        }
    ],
    "contexts": [
        {
            "name": "kind-kind",
            "context": {
                "cluster": "kind-kind",
                "user": "kind-kind"
            }
        }
    ],
    "current-context": "kind-kind"
}
```

**Comment by JanDeDobbeleer** [comment]
@jandhollander can you check if the latest versions shows what you expect

**Comment by jandhollander** [comment]
I believe so, yes.

Thanks a lot for the quick handling of this issue!
