### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by pashamcr** [JanDeDobbeleer/oh-my-posh#1586]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

A bug happened!
After updating 6.49.0, powershell starts with an error, what did I do wrong?
When I change the theme, I get different errors.

### Theme

agnoster and all others

### Log output

```shell
PowerShell 7.3.0-preview.1
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.


oh-my-posh fatal error rendering session segment:assignment to entry in nil map

goroutine 7 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.17.6/x64/src/runtime/debug/stack.go:24 +0x65
main.(*Segment).setStringValue.func1()
        /home/runner/work/oh-my-posh/oh-my-posh/src/segment.go:317 +0x58
panic({0x141e600, 0x1563bb0})
        /opt/hostedtoolcache/go/1.17.6/x64/src/runtime/panic.go:1038 +0x215
main.(*environment).environ(0xc000054d80)
        /home/runner/work/oh-my-posh/oh-my-posh/src/environment.go:241 +0x1e5
main.(*Context).init(0xc0001ee6c0, 0xc000069ef8)
        /home/runner/work/oh-my-posh/oh-my-posh/src/template.go:59 +0x1ff
main.(*textTemplate).render(0xc000069ef8)
        /home/runner/work/oh-my-posh/oh-my-posh/src/template.go:78 +0x17a
main.(*session).enabled(0xc0001d8700)
        /home/runner/work/oh-my-posh/oh-my-posh/src/segment_session.go:34 +0x130
main.(*Segment).enabled(...)
        /home/runner/work/oh-my-posh/oh-my-posh/src/segment.go:170
main.(*Segment).setStringValue(0xc000178a00, {0x1589c80, 0xc000054d80})
        /home/runner/work/oh-my-posh/oh-my-posh/src/segment.go:326 +0xa2
main.(*Block).setStringValues.func1(0x0)
        /home/runner/work/oh-my-posh/oh-my-posh/src/block.go:88 +0x65
created by main.(*Block).setStringValues
        /home/runner/work/oh-my-posh/oh-my-posh/src/block.go:86 +0x9d



oh-my-posh fatal error rendering path segment:assignment to entry in nil map

goroutine 8 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.17.6/x64/src/runtime/debug/stack.go:24 +0x65
main.(*Segment).setStringValue.func1()
        /home/runner/work/oh-my-posh/oh-my-posh/src/segment.go:317 +0x58
panic({0x141e600, 0x1563bb0})
        /opt/hostedtoolcache/go/1.17.6/x64/src/runtime/panic.go:1038 +0x215
main.(*environment).environ(0xc000054d80)
        /home/runner/work/oh-my-posh/oh-my-posh/src/environment.go:241 +0x1e5
main.(*Context).init(0xc0001ee870, 0xc000069ef8)
        /home/runner/work/oh-my-posh/oh-my-posh/src/template.go:59 +0x1ff
main.(*textTemplate).render(0xc000069ef8)
        /home/runner/work/oh-my-posh/oh-my-posh/src/template.go:78 +0x17a
main.(*path).string(0xc000057400)
        /home/runner/work/oh-my-posh/oh-my-posh/src/segment_path.go:101 +0x5fe
main.(*Segment).string(...)
        /home/runner/work/oh-my-posh/oh-my-posh/src/segment.go:166
main.(*Segment).setStringValue(0xc000178c00, {0x1589c80, 0xc000054d80})
        /home/runner/work/oh-my-posh/oh-my-posh/src/segment.go:327 +0xc5
main.(*Block).setStringValues.func1(0x0)
        /home/runner/work/oh-my-posh/oh-my-posh/src/block.go:88 +0x65
created by main.(*Block).setStringValues
        /home/runner/work/oh-my-posh/oh-my-posh/src/block.go:86 +0x9d
```

**Comment by JanDeDobbeleer** [comment]
Ow, I did make a mistake. Will fix.

**Comment by pashamcr** [comment]
Ok!
