### ISSUE TITLE
Random exception with oh-my-posh 7.8.0

### ISSUE THREAD

**Issue by 13xforever** [JanDeDobbeleer/oh-my-posh#1673]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Today I have updated to 7.8.0 and now I have random exceptions.

<details>
  <summary>fatal error: concurrent map writes</summary>

```
System.Management.Automation.RemoteException
goroutine 20 [running]:
runtime.throw({0x7f71b6, 0xc0002cc090})
        /opt/hostedtoolcache/go/1.17.6/x64/src/runtime/panic.go:1198 +0x76 fp=0xc0002bfcb0 sp=0xc0002bfc80 pc=0x236df6
runtime.mapassign_faststr(0xc00028c110, 0x1e, {0xc0002cc090, 0xf})
        /opt/hostedtoolcache/go/1.17.6/x64/src/runtime/map_faststr.go:211 +0x39c fp=0xc0002bfd18 sp=0xc0002bfcb0 pc=0x2132fc
oh-my-posh/environment.(*ShellEnvironment).TemplateCache(0xc00005cd20)
        /home/runner/work/oh-my-posh/oh-my-posh/src/environment/shell.go:618 +0x2ee fp=0xc0002bfe18 sp=0xc0002bfd18 pc=0x4f86ce
oh-my-posh/template.(*Context).init(...)
        /home/runner/work/oh-my-posh/oh-my-posh/src/template/text.go:36
oh-my-posh/template.(*Text).Render(0xc0002bfef8)
        /home/runner/work/oh-my-posh/oh-my-posh/src/template/text.go:49 +0x1b6 fp=0xc0002bfec8 sp=0xc0002bfe18 pc=0x55e456
oh-my-posh/engine.(*Segment).string(0xc0000e0600)
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/segment.go:285 +0x106 fp=0xc0002bff38 sp=0xc0002bfec8 pc=0x7009e6
oh-my-posh/engine.(*Segment).renderText(0xc0000e0600, {0x8d2080, 0xc00005cd20})
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/segment.go:309 +0xb0 fp=0xc0002bff80 sp=0xc0002bff38 pc=0x700ad0
oh-my-posh/engine.(*Block).renderSegmentsText.func1(0x0)
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/block.go:90 +0x65 fp=0xc0002bffc8 sp=0xc0002bff80 pc=0x6f3be5
oh-my-posh/engine.(*Block).renderSegmentsText·dwrap·2()
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/block.go:91 +0x2d fp=0xc0002bffe0 sp=0xc0002bffc8 pc=0x6f3b4d
runtime.goexit()
        /opt/hostedtoolcache/go/1.17.6/x64/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0002bffe8 sp=0xc0002bffe0 pc=0x264681
created by oh-my-posh/engine.(*Block).renderSegmentsText
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/block.go:88 +0x9d
System.Management.Automation.RemoteException
goroutine 1 [semacquire]:
sync.runtime_Semacquire(0x241720)
        /opt/hostedtoolcache/go/1.17.6/x64/src/runtime/sema.go:56 +0x25
sync.(*WaitGroup).Wait(0x6f39dd)
        /opt/hostedtoolcache/go/1.17.6/x64/src/sync/waitgroup.go:130 +0x71
oh-my-posh/engine.(*Block).renderSegmentsText(0xc0000960b0)
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/block.go:93 +0x199
oh-my-posh/engine.(*Engine).renderBlock(0xc000115de0, 0xc0000960b0)
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/engine.go:86 +0x126
oh-my-posh/engine.(*Engine).Render(0xc000115de0)
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/engine.go:60 +0x47
main.main()
        /home/runner/work/oh-my-posh/oh-my-posh/src/main.go:220 +0xe8a
System.Management.Automation.RemoteException
goroutine 18 [runnable]:
oh-my-posh/environment.(*ShellEnvironment).TemplateCache(0xc00005cd20)
        /home/runner/work/oh-my-posh/oh-my-posh/src/environment/shell.go:618 +0x2ee
oh-my-posh/template.(*Context).init(...)
        /home/runner/work/oh-my-posh/oh-my-posh/src/template/text.go:36
oh-my-posh/template.(*Text).Render(0xc00006fef8)
        /home/runner/work/oh-my-posh/oh-my-posh/src/template/text.go:49 +0x1b6
oh-my-posh/engine.(*Segment).string(0xc0000e0200)
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/segment.go:285 +0x106
oh-my-posh/engine.(*Segment).renderText(0xc0000e0200, {0x8d2080, 0xc00005cd20})
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/segment.go:309 +0xb0
oh-my-posh/engine.(*Block).renderSegmentsText.func1(0x0)
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/block.go:90 +0x65
created by oh-my-posh/engine.(*Block).renderSegmentsText
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/block.go:88 +0x9d
System.Management.Automation.RemoteException
goroutine 21 [runnable, locked to thread]:
syscall.Syscall9(0x7ff86ca82ed0, 0x7, 0xc000506000, 0x0, 0x0, 0x0, 0x3, 0x2000000, 0x0, 0x0, ...)
        /opt/hostedtoolcache/go/1.17.6/x64/src/runtime/syscall_windows.go:510 +0xdb
syscall.CreateFile(0xc000506000, 0x0, 0x0, 0x0, 0x3, 0x2000000, 0x0)
        /opt/hostedtoolcache/go/1.17.6/x64/src/syscall/zsyscall_windows.go:507 +0xd9
os.stat({0x7eb34e, 0x4}, {0xc000502000, 0x58}, 0xbc5a0)
        /opt/hostedtoolcache/go/1.17.6/x64/src/os/stat_windows.go:94 +0x49d
os.statNolog(...)
        /opt/hostedtoolcache/go/1.17.6/x64/src/os/stat_windows.go:106
os.Stat({0xc000502000, 0x58})
        /opt/hostedtoolcache/go/1.17.6/x64/src/os/stat.go:13 +0x45
os/exec.chkStat({0xc000502000, 0xc0000bc5a0})
        /opt/hostedtoolcache/go/1.17.6/x64/src/os/exec/lp_windows.go:19 +0x1e
os/exec.findExecutable({0xc0000bc5a0, 0x54}, {0xc0000e1700, 0xc, 0x0})
        /opt/hostedtoolcache/go/1.17.6/x64/src/os/exec/lp_windows.go:47 +0xd4
os/exec.LookPath({0x7ed334, 0x7ed334})
        /opt/hostedtoolcache/go/1.17.6/x64/src/os/exec/lp_windows.go:89 +0x41e
oh-my-posh/environment.(*ShellEnvironment).HasCommand(0xc00005cd20, {0x7ed334, 0x7})
        /home/runner/work/oh-my-posh/oh-my-posh/src/environment/shell.go:415 +0x125
oh-my-posh/segments.(*Git).shouldDisplay(0xc0000ea5a0)
        /home/runner/work/oh-my-posh/oh-my-posh/src/segments/git.go:145 +0x72
oh-my-posh/segments.(*Git).Enabled(0xc0000ea5a0)
        /home/runner/work/oh-my-posh/oh-my-posh/src/segments/git.go:115 +0x25
oh-my-posh/engine.(*Segment).renderText(0xc0000e0800, {0x8d2080, 0xc00005cd20})
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/segment.go:308 +0xa2
oh-my-posh/engine.(*Block).renderSegmentsText.func1(0x0)
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/block.go:90 +0x65
created by oh-my-posh/engine.(*Block).renderSegmentsText
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/block.go:88 +0x9d
```
</details>

### Theme

<details>
  <summary>I use my own theme</summary>
  
```json
{
    "$schema": "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json",
    "blocks": [
        {
            "alignment": "left",
            "segments": [
                {
                    "background": "#0077c2",
                    "foreground": "#ffffff",
                    "leading_diamond": "╭─",
                    "properties": {},
                    "style": "diamond",
                    "trailing_diamond": "",
                    "type": "shell"
                },
                {
                    "background": "#ef5350",
                    "foreground": "#FFFB38",
                    "leading_diamond": "",
                    "properties": {
                        "prefix": "<parentBackground></> ",
                        "root_icon": ""
                    },
                    "style": "diamond",
                    "trailing_diamond": "",
                    "type": "root"
                },
                {
                    "background": "#444444",
                    "foreground": "#E4E4E4",
                    "powerline_symbol": "",
                    "properties": {
                        "enable_hyperlink": true,
                        "style": "full"
                    },
                    "style": "powerline",
                    "type": "path"
                },
                {
                    "background": "#FFFB38",
                    "background_templates": [
                        "{{ if or (.Working.Changed) (.Staging.Changed) }}#ffeb95{{ end }}",
                        "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#c5e478{{ end }}",
                        "{{ if gt .Ahead 0 }}#C792EA{{ end }}",
                        "{{ if gt .Behind 0 }}#C792EA{{ end }}"
                    ],
                    "foreground": "#011627",
                    "powerline_symbol": "",
                    "properties": {
                        "branch_icon": " ",
                        "fetch_status": true,
                        "fetch_upstream_icon": true,
                        "template": "{{ .HEAD }} {{ if .Working.Changed }}{{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}<#ef5350>  {{ .Staging.String }}</>{{ end }}"
                    },
                    "style": "powerline",
                    "type": "git"
                }
            ],
            "type": "prompt"
        },
        {
            "alignment": "right",
            "segments": [
                {
                    "type": "exit",
                    "style": "diamond",
                    "leading_diamond": "\uE0B6",
                    "trailing_diamond": "",
                    "foreground": "#ffffff",
                    "background": "#154929",
                    "background_templates": [
                        "{{ if gt .Code 0 }}#f1184c{{ end }}"
                    ],
                    "properties": {
                        "prefix": " ",
                        "postfix": " ",
                        "template": "{{ if gt .Code 0 }}{{ .Code | printf \"%#08x\" }}{{ else }}\uf42e {{ end }}",
                        "always_enabled": true
                    }
                },
                {
                    "type": "executiontime",
                    "style": "powerline",
                    "foreground": "#ffffff",
                    "background": "#83769c",
                    "powerline_symbol": "\uE0C4 ",
                    "properties": {
                        "prefix": "\uf651 ",
                        "threshold": 0
                    }
                },
                {
                    "type": "time",
                    "style": "diamond",
                    "trailing_diamond": "\uE0B4",
                    "background": "#40c4ff",
                    "foreground": "#ffffff",
                    "properties": {
                        "prefix": "\uf43a ",
                        "postfix": " ",
                        "time_format": "15:04"
                    }
                }
            ],
            "type": "prompt"
        },
        {
            "alignment": "left",
            "newline": true,
            "segments": [
                {
                    "foreground": "#21c7c7",
                    "properties": {
                        "postfix": "",
                        "prefix": "",
                        "text": "╰─"
                    },
                    "style": "plain",
                    "type": "text"
                },
                {
                    "foreground": "#e0f8ff",
                    "properties": {
                        "always_enabled": true,
                        "display_exit_code": false,
                        "error_color": "#ef5350",
                        "prefix": "❯"
                    },
                    "style": "plain",
                    "type": "exit"
                }
            ],
            "type": "prompt"
        }
    ],
    "final_space": false,
    "osc99": true
}
```
</details>

The only suspicious seciton I could think of is the exit code formatting
```json
"template": "{{ if gt .Code 0 }}{{ .Code | printf \"%#08x\" }}{{ else }}\uf42e {{ end }}"
```

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```shell
Version: 7.8.0

Segments:

ConsoleTitle(false)  -   0 ms -
shell(true)          -   1 ms - ╭─ pwsh
root(false)          -   0 ms -
path(true)           -   0 ms -  ~
git(false)           -  11 ms -
exit(true)           -   0 ms -  0x00000539
executiontime(true)  -   1 ms -   9.001s
time(true)           -   0 ms -   21:32 
text(true)           -   0 ms - ╰─
exit(true)           -   1 ms - ❯

Run duration: 17.1023ms

Cache path: C:\Users\username\AppData\Local/oh-my-posh

Logs:

2022/02/03 21:32:40 Args duration: 0s, args:
2022/02/03 21:32:40 Args duration: 0s, args:
2022/02/03 21:32:40 Args duration: 0s, args:
2022/02/03 21:32:40 Shell duration: 0s, args:
2022/02/03 21:32:40 debug: Getenv

2022/02/03 21:32:40 Getenv duration: 0s, args: OMP_CACHE_DISABLED
2022/02/03 21:32:40 debug: Pwd
C:\Users\username
2022/02/03 21:32:40 Pwd duration: 0s, args:
2022/02/03 21:32:40 debug: Home
C:\Users\username
2022/02/03 21:32:40 PathSeperator duration: 0s, args:
2022/02/03 21:32:40 PathSeperator duration: 0s, args:
2022/02/03 21:32:40 debug: Pwd
C:\Users\username
2022/02/03 21:32:40 Pwd duration: 0s, args:
2022/02/03 21:32:40 debug: Home
C:\Users\username
2022/02/03 21:32:40 Shell duration: 0s, args:
2022/02/03 21:32:40 Root duration: 0s, args:
2022/02/03 21:32:40 Shell duration: 0s, args:
2022/02/03 21:32:40 ErrorCode duration: 0s, args:
2022/02/03 21:32:40 IsWsl duration: 0s, args:
2022/02/03 21:32:40 debug: Pwd
C:\Users\username
2022/02/03 21:32:40 Pwd duration: 0s, args:
2022/02/03 21:32:40 debug: Home
C:\Users\username
2022/02/03 21:32:40 PathSeperator duration: 0s, args:
2022/02/03 21:32:40 PathSeperator duration: 0s, args:
2022/02/03 21:32:40 User duration: 0s, args:
2022/02/03 21:32:40 Host duration: 0s, args:
2022/02/03 21:32:40 GOOS duration: 0s, args:
2022/02/03 21:32:40 TemplateCache duration: 613.9µs, args:
2022/02/03 21:32:40 debug: Pwd
C:\Users\username
2022/02/03 21:32:40 Pwd duration: 0s, args:
2022/02/03 21:32:40 debug: Home
C:\Users\username
2022/02/03 21:32:40 Root duration: 0s, args:
2022/02/03 21:32:40 debug: Pwd
C:\Users\username
2022/02/03 21:32:40 Pwd duration: 0s, args:
2022/02/03 21:32:40 debug: Home
C:\Users\username
2022/02/03 21:32:40 debug: Pwd
C:\Users\username
2022/02/03 21:32:40 Pwd duration: 0s, args:
2022/02/03 21:32:40 Args duration: 0s, args:
2022/02/03 21:32:40 debug: Home
C:\Users\username
2022/02/03 21:32:40 GOOS duration: 0s, args:
2022/02/03 21:32:40 GOOS duration: 0s, args:
2022/02/03 21:32:40 PathSeperator duration: 0s, args:
2022/02/03 21:32:40 GOOS duration: 0s, args:
2022/02/03 21:32:40 IsWsl duration: 0s, args:
2022/02/03 21:32:40 StackCount duration: 0s, args:
2022/02/03 21:32:40 TemplateCache duration: 0s, args:
2022/02/03 21:32:40 debug: Pwd
C:\Users\username
2022/02/03 21:32:40 Pwd duration: 0s, args:
2022/02/03 21:32:40 debug: Home
C:\Users\username
2022/02/03 21:32:40 GOOS duration: 0s, args:
2022/02/03 21:32:40 HasCommand duration: 11.347ms, args: git.exe
2022/02/03 21:32:40 debug: Pwd
C:\Users\username
2022/02/03 21:32:40 Pwd duration: 0s, args:
2022/02/03 21:32:40 error: HasParentFilePath
CreateFile C:\.git: The system cannot find the file specified.
2022/02/03 21:32:40 HasParentFilePath duration: 120.7µs, args: .git
2022/02/03 21:32:40 debug: Pwd
C:\Users\username
2022/02/03 21:32:40 Pwd duration: 0s, args:
2022/02/03 21:32:40 debug: Home
C:\Users\username
2022/02/03 21:32:40 ErrorCode duration: 0s, args:
2022/02/03 21:32:40 TemplateCache duration: 0s, args:
2022/02/03 21:32:40 TemplateCache duration: 0s, args:
2022/02/03 21:32:40 debug: Pwd
C:\Users\username
2022/02/03 21:32:40 Pwd duration: 0s, args:
2022/02/03 21:32:40 debug: Home
C:\Users\username
2022/02/03 21:32:40 ExecutionTime duration: 0s, args:
2022/02/03 21:32:40 TemplateCache duration: 0s, args:
2022/02/03 21:32:40 TemplateCache duration: 0s, args:
2022/02/03 21:32:40 debug: Pwd
C:\Users\username
2022/02/03 21:32:40 Pwd duration: 0s, args:
2022/02/03 21:32:40 debug: Home
C:\Users\username
2022/02/03 21:32:40 TemplateCache duration: 0s, args:
2022/02/03 21:32:40 debug: Pwd
C:\Users\username
2022/02/03 21:32:40 Pwd duration: 0s, args:
2022/02/03 21:32:40 debug: Home
C:\Users\username
2022/02/03 21:32:40 TemplateCache duration: 0s, args:
2022/02/03 21:32:40 debug: Pwd
C:\Users\username
2022/02/03 21:32:40 Pwd duration: 0s, args:
2022/02/03 21:32:40 debug: Home
C:\Users\username
2022/02/03 21:32:40 ErrorCode duration: 0s, args:
2022/02/03 21:32:40 TemplateCache duration: 0s, args:
2022/02/03 21:32:40 TemplateCache duration: 0s, args:
2022/02/03 21:32:40 debug: Getenv
C:\Users\username\AppData\Local
2022/02/03 21:32:40 Getenv duration: 0s, args: LOCALAPPDATA
2022/02/03 21:32:40 CachePath duration: 0s, args:
```

**Comment by JanDeDobbeleer** [comment]
@13xforever I noticed it too just now, will fix.

**Comment by JanDeDobbeleer** [comment]
@13xforever sorry for this. I thought my COVID dumbness was over but it seems I'm still in a bit of a woozy state. This is a very stupid issue I introduced because I thought I was smart while in reality I was pretty stupid.
