### ISSUE TITLE
v7.73.0 failing to launch

### ISSUE THREAD

**Issue by ThirdEyeSqueegee** [JanDeDobbeleer/oh-my-posh#2175]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

oh-my-posh fails to launch on Windows Terminal Preview on Windows 11 after updating to v7.73.0. Fails both with plain initialization `oh-my-posh init pwsh` and initialization with config. Note the attached output of `oh-my-posh debug` is too long to include in full, but the remainder is just a series of similar goroutine deadlock error reports. 

### Theme

`oh-my-posh init pwsh --config $env:POSH_THEMES_PATH/wopian.omp.json | Invoke-Expression`

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [semacquire]:
sync.runtime_SemacquireMutex(0xc00011b7c8?, 0xc8?, 0xc00011b788?)
        /opt/hostedtoolcache/go/1.18.0/x64/src/runtime/sema.go:71 +0x25
sync.(*Mutex).lockSlow(0xc00024c064)
        /opt/hostedtoolcache/go/1.18.0/x64/src/sync/mutex.go:162 +0x165
sync.(*Mutex).Lock(...)
        /opt/hostedtoolcache/go/1.18.0/x64/src/sync/mutex.go:81
oh-my-posh/environment.(*ShellEnvironment).Home(0xc00024c000)
        /home/runner/work/oh-my-posh/oh-my-posh/src/environment/windows.go:58 +0x65
oh-my-posh/environment.(*ShellEnvironment).DirMatchesOneOf(0xc00024c000, {0xc000089230, 0xe}, {0x1ba0920, 0x0, 0x0})
        /home/runner/work/oh-my-posh/oh-my-posh/src/environment/shell.go:727 +0x114
oh-my-posh/engine.(*Segment).cwdExcluded(0xc0000da000)
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/segment.go:216 +0xe2
oh-my-posh/engine.(*Segment).shouldIncludeFolder(0xc0000da000)
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/segment.go:185 +0x36
oh-my-posh/engine.(*Segment).renderText(0xc0000da000, {0x12403d0?, 0xc00024c000?})
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/segment.go:339 +0x7b
oh-my-posh/engine.(*Block).debug(0xc0000d8000)
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/block.go:180 +0x13a
oh-my-posh/engine.(*Engine).PrintDebug(0xc00011bcf0, {0x12319a4?, 0x0?})
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/engine.go:186 +0x60d
oh-my-posh/cli.glob..func6(0x1b3e7c0?, {0x1ba0920?, 0x0?, 0x0?})
        /home/runner/work/oh-my-posh/oh-my-posh/src/cli/debug.go:50 +0x2e5
github.com/spf13/cobra.(*Command).execute(0x1b3e7c0, {0x1ba0920, 0x0, 0x0})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x1b3d8c0)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
oh-my-posh/cli.Execute({0x12319a4?, 0xc00004e000?})
        /home/runner/work/oh-my-posh/oh-my-posh/src/cli/root.go:40 +0x51
main.main()
        /home/runner/work/oh-my-posh/oh-my-posh/src/main.go:10 +0x27
```

**Comment by JanDeDobbeleer** [comment]
@ThirdEyeSqueegee I know what's causing this indeed. Will fix. Should've validated 🤦🏻‍♂️

**Comment by JanDeDobbeleer** [comment]
@ThirdEyeSqueegee the funny thing is, this doesn't happen on my machine. One of these days I guess...
