### ISSUE TITLE
Unable to use Connect-ExchangeOnline without credential flag

### ISSUE THREAD

**Issue by noxxxxxious** [JanDeDobbeleer/oh-my-posh#2506]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

When using `Connect-ExchangeOnline` without the credential flag, normally PowerShell will open a window to authenticate an account. When using oh-my-posh, creation of this window fails. It is possible to get around this by supplying credentials; however, it's impossible to log into an account with 2FA enabled because of this. When disabling oh-my-posh, the login window is created with no issue.

```
Error Acquiring Token:
System.Threading.ThreadStateException: ActiveX control '8856f961-340a-11d0-a96b-00c04fd705a2' cannot be instantiated because the current thread is not in a single-threaded apartment.
   at System.Windows.Forms.WebBrowserBase..ctor(String clsidString)
   at System.Windows.Forms.WebBrowser..ctor()
   at Microsoft.Identity.Client.Platforms.Features.WinFormsLegacyWebUi.WindowsFormsWebAuthenticationDialogBase..ctor(Object ownerWindow)
   at Microsoft.Identity.Client.Platforms.Features.WinFormsLegacyWebUi.WindowsFormsWebAuthenticationDialog..ctor(Object ownerWindow)
   at Microsoft.Identity.Client.Platforms.Features.WinFormsLegacyWebUi.InteractiveWebUI.OnAuthenticate()
   at Microsoft.Identity.Client.Platforms.Features.WinFormsLegacyWebUi.WebUI.<>c__DisplayClass20_0.<AcquireAuthorizationAsync>b__1(Object tcs)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Platforms.Features.WinFormsLegacyWebUi.WebUI.<AcquireAuthorizationAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.<FetchAuthCodeAndPkceInternalAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.<FetchAuthCodeAndPkceVerifierAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.<GetTokenResponseAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.<ExecuteAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<RunAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.ApiConfig.Executors.PublicClientExecutor.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Exchange.Management.AdminApiProvider.Authentication.MSALTokenProvider.<GetAccessTokenAsync>d__22.MoveNext()
New-ExoPSSession : One or more errors occurred.
At C:\Program
Files\WindowsPowerShell\Modules\ExchangeOnlineManagement\2.0.5\netFramework\ExchangeOnlineManagement.psm1:475 char:30
+ ... PSSession = New-ExoPSSession -ExchangeEnvironmentName $ExchangeEnviro ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-ExoPSSession], AggregateException
    + FullyQualifiedErrorId : System.AggregateException,Microsoft.Exchange.Management.ExoPowershellSnapin.NewExoPSSess
   ion
```

### Theme

sonicboom_dark

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
﬌  oh-my-posh debug

Version: 8.15.2

Segments:

ConsoleTitle(false)  -   0 ms -
root(false)          -   0 ms -
os(true)             -   0 ms -  
path(true)           -   0 ms -  
git(false)           -   6 ms -
executiontime(true)  -   0 ms -  0s 
session(true)        -   0 ms -  [redacted]
time(true)           -   0 ms -   9:42:06 AM 
exit(true)           -   0 ms - ﬌

Run duration: 22.3658ms

Cache path: C:\Users\[redacted]\AppData\Local\oh-my-posh

Config path: C:\Program Files (x86)\oh-my-posh\themes\sonicboom_dark.omp.json

Logs:

2022/07/11 09:42:06 debug: Getenv
C:\Users\[redacted]\AppData\Local
2022/07/11 09:42:06 Getenv duration: 0s, args: LOCALAPPDATA
2022/07/11 09:42:06 CachePath duration: 0s, args:
2022/07/11 09:42:06 debug: Getenv
C:\Program Files (x86)\oh-my-posh\themes\sonicboom_dark.omp.json
2022/07/11 09:42:06 Getenv duration: 0s, args: POSH_THEME
2022/07/11 09:42:06 Shell duration: 12.4061ms, args:
2022/07/11 09:42:06 resolveConfigPath duration: 12.4061ms, args:
2022/07/11 09:42:06 Init duration: 12.4061ms, args:
2022/07/11 09:42:06 Flags duration: 0s, args:
2022/07/11 09:42:06 config.loadConfig duration: 1.03ms, args:
2022/07/11 09:42:06 Flags duration: 0s, args:
2022/07/11 09:42:06 debug: Getenv

2022/07/11 09:42:06 Getenv duration: 0s, args: OMP_CACHE_DISABLED
2022/07/11 09:42:06 WindowsRegistryKeyValue duration: 0s, args: HKEY_CURRENT_USER\Software\Microsoft\Windows\DWM\ColorizationColor
2022/07/11 09:42:06 PathSeparator duration: 0s, args:
2022/07/11 09:42:06 PathSeparator duration: 0s, args:
2022/07/11 09:42:06 PathSeparator duration: 0s, args:
2022/07/11 09:42:06 PathSeparator duration: 0s, args:
2022/07/11 09:42:06 PathSeparator duration: 0s, args:
2022/07/11 09:42:06 PathSeparator duration: 0s, args:
2022/07/11 09:42:06 PathSeparator duration: 0s, args:
2022/07/11 09:42:06 PathSeparator duration: 0s, args:
2022/07/11 09:42:06 PathSeparator duration: 0s, args:
2022/07/11 09:42:06 PathSeparator duration: 0s, args:
2022/07/11 09:42:06 PathSeparator duration: 0s, args:
2022/07/11 09:42:06 PathSeparator duration: 0s, args:
2022/07/11 09:42:06 PathSeparator duration: 0s, args:
2022/07/11 09:42:06 PathSeparator duration: 0s, args:
2022/07/11 09:42:06 PathSeparator duration: 0s, args:
2022/07/11 09:42:06 PathSeparator duration: 0s, args:
2022/07/11 09:42:06 PathSeparator duration: 0s, args:
2022/07/11 09:42:06 PathSeparator duration: 0s, args:
2022/07/11 09:42:06 PathSeparator duration: 0s, args:
2022/07/11 09:42:06 debug: WindowsRegistryKeyValue
ColorizationColor(DWORD): 0xC4107C10
2022/07/11 09:42:06 Root duration: 0s, args:
2022/07/11 09:42:06 Shell duration: 0s, args:
2022/07/11 09:42:06 ErrorCode duration: 0s, args:
2022/07/11 09:42:06 IsWsl duration: 0s, args:
2022/07/11 09:42:06 debug: Pwd
C:\Users\[redacted]
2022/07/11 09:42:06 Pwd duration: 0s, args:
2022/07/11 09:42:06 debug: Home
C:\Users\[redacted]
2022/07/11 09:42:06 PathSeparator duration: 0s, args:
2022/07/11 09:42:06 PathSeparator duration: 0s, args:
2022/07/11 09:42:06 debug: User
[redacted]
2022/07/11 09:42:06 User duration: 0s, args:
2022/07/11 09:42:06 debug: Host
[redacted]
2022/07/11 09:42:06 Host duration: 998.4µs, args:
2022/07/11 09:42:06 GOOS duration: 0s, args:
2022/07/11 09:42:06 TemplateCache duration: 998.4µs, args:
2022/07/11 09:42:06 Flags duration: 0s, args:
2022/07/11 09:42:06 debug: Pwd
C:\Users\[redacted]
2022/07/11 09:42:06 Pwd duration: 0s, args:
2022/07/11 09:42:06 debug: Home
C:\Users\[redacted]
2022/07/11 09:42:06 GOOS duration: 0s, args:
2022/07/11 09:42:06 Root duration: 0s, args:
2022/07/11 09:42:06 debug: Pwd
C:\Users\[redacted]
2022/07/11 09:42:06 Pwd duration: 0s, args:
2022/07/11 09:42:06 debug: Home
C:\Users\[redacted]
2022/07/11 09:42:06 GOOS duration: 0s, args:
2022/07/11 09:42:06 GOOS duration: 0s, args:
2022/07/11 09:42:06 TemplateCache duration: 0s, args:
2022/07/11 09:42:06 TemplateCache duration: 0s, args:
2022/07/11 09:42:06 Shell duration: 0s, args:
2022/07/11 09:42:06 debug: Pwd
C:\Users\[redacted]
2022/07/11 09:42:06 Pwd duration: 0s, args:
2022/07/11 09:42:06 debug: Home
C:\Users\[redacted]
2022/07/11 09:42:06 GOOS duration: 0s, args:
2022/07/11 09:42:06 debug: Pwd
C:\Users\[redacted]
2022/07/11 09:42:06 Pwd duration: 0s, args:
2022/07/11 09:42:06 Flags duration: 0s, args:
2022/07/11 09:42:06 debug: Pwd
C:\Users\[redacted]
2022/07/11 09:42:06 Pwd duration: 0s, args:
2022/07/11 09:42:06 debug: Home
C:\Users\[redacted]
2022/07/11 09:42:06 GOOS duration: 0s, args:
2022/07/11 09:42:06 GOOS duration: 0s, args:
2022/07/11 09:42:06 PathSeparator duration: 0s, args:
2022/07/11 09:42:06 Flags duration: 0s, args:
2022/07/11 09:42:06 debug: Pwd
C:\Users\[redacted]
2022/07/11 09:42:06 Pwd duration: 0s, args:
2022/07/11 09:42:06 debug: Home
C:\Users\[redacted]
2022/07/11 09:42:06 GOOS duration: 0s, args:
2022/07/11 09:42:06 GOOS duration: 0s, args:
2022/07/11 09:42:06 PathSeparator duration: 0s, args:
2022/07/11 09:42:06 PathSeparator duration: 0s, args:
2022/07/11 09:42:06 PathSeparator duration: 0s, args:
2022/07/11 09:42:06 GOOS duration: 0s, args:
2022/07/11 09:42:06 IsWsl duration: 0s, args:
2022/07/11 09:42:06 StackCount duration: 0s, args:
2022/07/11 09:42:06 DirIsWritable duration: 0s, args:
2022/07/11 09:42:06 TemplateCache duration: 0s, args:
2022/07/11 09:42:06 TemplateCache duration: 0s, args:
2022/07/11 09:42:06 Shell duration: 0s, args:
2022/07/11 09:42:06 debug: Pwd
C:\Users\[redacted]
2022/07/11 09:42:06 Pwd duration: 0s, args:
2022/07/11 09:42:06 debug: Home
C:\Users\[redacted]
2022/07/11 09:42:06 GOOS duration: 0s, args:
2022/07/11 09:42:06 GOOS duration: 0s, args:
2022/07/11 09:42:06 HasCommand duration: 6.2245ms, args: git.exe
2022/07/11 09:42:06 debug: Pwd
C:\Users\[redacted]
2022/07/11 09:42:06 Pwd duration: 0s, args:
2022/07/11 09:42:06 error: HasParentFilePath
CreateFile C:\.git: The system cannot find the file specified.
2022/07/11 09:42:06 HasParentFilePath duration: 614.8µs, args: .git
2022/07/11 09:42:06 debug: Pwd
C:\Users\[redacted]
2022/07/11 09:42:06 Pwd duration: 0s, args:
2022/07/11 09:42:06 debug: Home
C:\Users\[redacted]
2022/07/11 09:42:06 GOOS duration: 0s, args:
2022/07/11 09:42:06 ExecutionTime duration: 0s, args:
2022/07/11 09:42:06 TemplateCache duration: 0s, args:
2022/07/11 09:42:06 TemplateCache duration: 0s, args:
2022/07/11 09:42:06 Shell duration: 0s, args:
2022/07/11 09:42:06 Flags duration: 0s, args:
2022/07/11 09:42:06 debug: Pwd
C:\Users\[redacted]
2022/07/11 09:42:06 Pwd duration: 0s, args:
2022/07/11 09:42:06 debug: Home
C:\Users\[redacted]
2022/07/11 09:42:06 GOOS duration: 0s, args:
2022/07/11 09:42:06 debug: Getenv

2022/07/11 09:42:06 Getenv duration: 0s, args: SSH_CONNECTION
2022/07/11 09:42:06 debug: Getenv

2022/07/11 09:42:06 Getenv duration: 0s, args: SSH_CLIENT
2022/07/11 09:42:06 TemplateCache duration: 0s, args:
2022/07/11 09:42:06 TemplateCache duration: 0s, args:
2022/07/11 09:42:06 Shell duration: 0s, args:
2022/07/11 09:42:06 debug: Pwd
C:\Users\[redacted]
2022/07/11 09:42:06 Pwd duration: 0s, args:
2022/07/11 09:42:06 debug: Home
C:\Users\[redacted]
2022/07/11 09:42:06 GOOS duration: 0s, args:
2022/07/11 09:42:06 TemplateCache duration: 0s, args:
2022/07/11 09:42:06 TemplateCache duration: 0s, args:
2022/07/11 09:42:06 Shell duration: 0s, args:
2022/07/11 09:42:06 Flags duration: 0s, args:
2022/07/11 09:42:06 debug: Pwd
C:\Users\[redacted]
2022/07/11 09:42:06 Pwd duration: 0s, args:
2022/07/11 09:42:06 debug: Home
C:\Users\[redacted]
2022/07/11 09:42:06 GOOS duration: 0s, args:
2022/07/11 09:42:06 ErrorCode duration: 0s, args:
2022/07/11 09:42:06 TemplateCache duration: 0s, args:
2022/07/11 09:42:06 TemplateCache duration: 0s, args:
2022/07/11 09:42:06 Shell duration: 0s, args:
2022/07/11 09:42:06 TemplateCache duration: 0s, args:
2022/07/11 09:42:06 debug: Getenv
C:\Users\[redacted]\AppData\Local
2022/07/11 09:42:06 Getenv duration: 0s, args: LOCALAPPDATA
2022/07/11 09:42:06 CachePath duration: 0s, args:
2022/07/11 09:42:06 Flags duration: 0s, args:
```
```

**Comment by JanDeDobbeleer** [comment]
@seanmwfried that's not a bug for oh-my-posh but either PowerShell or that cmdlet's creator.
