### ISSUE TITLE
sysinfo segment fails on TermUX

### ISSUE THREAD

**Issue by mateuszdrab** [JanDeDobbeleer/oh-my-posh#2672]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I have a shared theme between various devices and one of them is termux, a terminal emulator on Android.
On this device omp fails to acquire system stats  (probably expected due to the way termux works)
I'd like that the error is handled silently instead of printing the panic everytime omp is invoked.
I'm not able to get any parts of the template to render, on this device I have to remove the sysinfo segment to stop the error.

### Theme

```{
  "$schema": "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json",
  "blocks": [
    {
      "alignment": "left",
      "segments": [
        {
          "background": "#af0c0c",
          "foreground": "#ffffff",
          "leading_diamond": "\ue0b6",
          "trailing_diamond": "\ue0b0",
          "style": "diamond",
          "properties": {
            "windows": "\ue62a "
          },
          "template": " {{.Icon}}{{ if .WSL }} WSL{{ end }} ",
          "type": "os"
        },
        {
          "background": "#4f4d4d",
          "foreground": "#fff",
          "powerline_symbol": "\ue0b0",
          "style": "powerline",
          "template": " {{ if .SSHSession }}\uf817 {{ end }}{{ .UserName }}@{{ .HostName }} ",
          "type": "session"
        },
        {
          "background": "#0077c2",
          "foreground": "#ffffff",
          "leading_diamond": "<transparent,background>\ue0b0</>",
          "trailing_diamond": "\ue0b4",
          "style": "diamond",
          "template": " \uf489 {{ .Name }} ",
          "type": "shell"
        }
      ],
      "type": "prompt"
    },
    {
      "alignment": "right",
      "segments": [
        {
          "background": "#2b8e6d",
          "foreground": "#000000",
          "leading_diamond": "\ue0b6",
          "style": "diamond",
          "template": " \uf85a CPU: {{ round .PhysicalPercentUsed .Precision }}% LOAD: {{ .Load1 }} {{ .Load5 }} {{ .Load15 }} MEM: {{ (div ((sub .PhysicalTotalMemory .PhysicalFreeMemory)|float64) 1000000000.0) }}/{{ (div .PhysicalTotalMemory 1000000000.0) }}GB ",
          "trailing_diamond": "<transparent,background>\ue0b2</>",
          "type": "sysinfo"
        },
        {
          "background": "#f36943",
          "background_templates": [
            "{{if eq \"Charging\" .State.String}}#40c4ff{{end}}",
            "{{if eq \"Discharging\" .State.String}}#ff5722{{end}}",
            "{{if eq \"Full\" .State.String}}#4caf50{{end}}"
          ],
          "foreground": "#ffffff",
          "invert_powerline": true,
          "powerline_symbol": "\ue0b2",
          "properties": {
            "charged_icon": "\ue22f ",
            "charging_icon": "\uf583 ",
            "discharging_icon": "\uf582 "
          },
          "style": "powerline",
          "template": " {{ if not .Error }}{{ .Icon }}{{ .Percentage }}{{ end }}{{ .Error }}\uf295 ",
          "type": "battery"
        },
        {
          "background": "#2e9599",
          "foreground": "#111111",
          "invert_powerline": true,
          "leading_diamond": "\ue0b2",
          "trailing_diamond": "\ue0b4",
          "style": "diamond",
          "template": " \uf017 {{ .CurrentDate | date .Format }} ",
          "type": "time"
        }
      ],
      "type": "prompt"
    },
    {
      "alignment": "left",
      "newline": true,
      "segments": [
        {
          "background": "#00c27e",
          "foreground": "#ffffff",
          "leading_diamond": "\ue0b6",
          "properties": {
            "style": "folder"
          },
          "style": "diamond",
          "template": " \uf07b {{ .Path }} ",
          "type": "path",
          "trailing_diamond": "\ue0b0"
        },
        {
          "background": "#fffb38",
          "background_templates": [
            "{{ if or (.Working.Changed) (.Staging.Changed) }}#FF9248{{ end }}",
            "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#ff4500{{ end }}",
            "{{ if gt .Ahead 0 }}#B388FF{{ end }}",
            "{{ if gt .Behind 0 }}#B388FF{{ end }}"
          ],
          "foreground": "#193549",
          "leading_diamond": "<transparent,background>\ue0b0</>",
          "properties": {
            "branch_max_length": 25,
            "fetch_stash_count": true,
            "fetch_status": true,
            "fetch_upstream_icon": true
          },
          "style": "diamond",
          "trailing_diamond": "\ue0b0",
          "template": " {{ .UpstreamIcon }}{{ .HEAD }}{{ .BranchStatus }}{{ if .Working.Changed }} \uf044 {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }} \uf046 {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }} \uf692 {{ .StashCount }}{{ end }} ",
          "type": "git"
        },
        {
          "background": "#4f4d4d",
          "foreground": "#ffffff",
          "properties": {
            "always_enabled": true
          },
          "style": "diamond",
          "template": " {{ .FormattedMs }} ",
          "type": "executiontime",
          "leading_diamond": "<transparent,background>\ue0b0</>",
          "trailing_diamond": "\ue0b0"
        },
        {
          "background": "#4f4d4d",
          "background_templates": [
            "{{ if gt .Code 0 }}#f1184c{{ end }}"
          ],
          "foreground": "#ffffff",
          "leading_diamond": "<transparent,background>\ue0b0</>",
          "properties": {
            "always_enabled": true
          },
          "style": "diamond",
          "template": " {{ if gt .Code 0 }}\uf00d {{ .Meaning }}{{ else }}\uf42e{{ end }} ",
          "trailing_diamond": "\ue0b4",
          "type": "exit"
        }
      ],
      "type": "prompt"
    },
    {
      "alignment": "right",
      "segments": [
        {
          "background": "#ebcc34",
          "foreground": "#000000",
          "leading_diamond": "\ue0b6",
          "style": "diamond",
          "template": " \ufd31 {{.Context}} {{if .Namespace}}- {{.Namespace}}{{end}} ",
          "trailing_diamond": "\ue0b4 ",
          "type": "kubectl"
        },
        {
          "background": "#9ec3f0",
          "foreground": "#000000",
          "leading_diamond": "\ue0b6",
          "trailing_diamond": "\ue0b4",
          "style": "diamond",
          "template": " \ufd03 {{ .Name }} ({{ if .EnvironmentName | contains \"AzureCloud\" }}{{ \"Global\" }}{{ else }}{{ .EnvironmentName }}{{ end }}) ",
          "type": "az"
        }
      ],
      "type": "prompt"
    },
    {
      "alignment": "left",
      "newline": true,
      "segments": [
        {
          "background": "#b81313",
          "foreground": "#111111",
          "style": "plain",
          "template": " \uf0e7 ",
          "type": "root"
        },
        {
          "foreground": "#E06C75",
          "style": "plain",
          "template": " > ",
          "type": "text"
        }
      ],
      "type": "prompt"
    }
  ],
  "console_title_template": "{{ .Shell }} in {{ .Folder }}",
  "final_space": true,
  "version": 2
}
```

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

bash

### Log output

```Shell
oh-my-posh fatal error rendering sysinfo segment:runtime error: index out of range [0] with length 0

goroutine 15 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.18.4/x64/src/runtime/debug/stack.go:24 +0x68
oh-my-posh/engine.(*Segment).SetEnabled.func1()
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/segment.go:371 +0x40
panic({0x71c900, 0x4000446018})
        /opt/hostedtoolcache/go/1.18.4/x64/src/runtime/panic.go:838 +0x20c
oh-my-posh/segments.(*SystemInfo).Init(0x400041c140, {0x8ab100?, 0x400040e150?}, {0x8afdf0?, 0x4000080b40?})
        /home/runner/work/oh-my-posh/oh-my-posh/src/segments/sysinfo.go:81 +0x264
oh-my-posh/engine.(*Segment).mapSegmentWithWriter(0x40000cf340, {0x8afdf0?, 0x4000080b40})
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/segment.go:333 +0x1884
oh-my-posh/engine.(*Segment).SetEnabled(0x40000cf340, {0x8afdf0, 0x4000080b40})
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/segment.go:375 +0x58
oh-my-posh/engine.(*Block).setEnabledSegments.func1(0x0?)
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/block.go:108 +0x5c
created by oh-my-posh/engine.(*Block).setEnabledSegments
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/block.go:106 +0x90

2022/08/17 08:48:30 error: Render
template:   CPU: {{ round .Data.PhysicalPercentUsed .Data.Precision }}&{%!L(uintptr= 16) %!L(uintptr= 16) %!L(uint32= 153969726) %!L(reflect.tflag= 7) %!L(uint8= 8) %!L(uint8= 8) %!L(uint8= 20) %!L(func(unsafe.Pointer, unsafe.Pointer) bool= 0x13b30) %!L(*uint8= 0x8a05c0) %!L(reflect.nameOff= 77424) %!L(reflect.typeOff= 269504)}OAD: {{ .Data.Load1 }} {{ .Data.Load5 }} {{ .Data.Load15 }} MEM: {{ (div ((sub .Data.PhysicalTotalMemory .Data.PhysicalFreeMemory)|float64) 1000000000.0) }}/{{ (div .Data.PhysicalTotalMemory 1000000000.0) }}GB :1:24: executing " \uf85a CPU: {{ round .Data.PhysicalPercentUsed .Data.Precision }}% LOAD: {{ .Data.Load1 }} {{ .Data.Load5 }} {{ .Data.Load15 }} MEM: {{ (div ((sub .Data.PhysicalTotalMemory .Data.PhysicalFreeMemory)|float64) 1000000000.0) }}/{{ (div .Data.PhysicalTotalMemory 1000000000.0) }}GB " at <.Data.PhysicalPercentUsed>: nil pointer evaluating PhysicalPercentUsed.%!s(MISSING)
```

**Comment by JanDeDobbeleer** [comment]
@mateuszdrab yup, that's a bug. We do not validate the length of that array and it fails. Will add that validation, thanks for bringing that to my attention 🙏🏻

**Comment by mateuszdrab** [comment]
Awesome, thanks for checking it so quickly.

**Comment by mateuszdrab** [comment]
Thanks! I can confirm it works now
