### ISSUE TITLE
oh-my-posh not working 

### ISSUE THREAD

**Issue by kid1412621** [JanDeDobbeleer/oh-my-posh#2680]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

nothing change after I setup in profile. Already rebooted.
win11 + windows terminal.
my profile:
```powershell
$OutputEncoding = [console]::InputEncoding = [console]::OutputEncoding = New-Object System.Text.UTF8Encoding
# Oh-My-Posh (`winget install oh-my-posh`)
$env:POSH_GIT_ENABLED = $true
oh-my-posh init pwsh --config "$env:POSH_THEMES_PATH/star.omp.json" | Invoke-Expression
Enable-PoshTooltips
```

Even I executed `oh-my-posh init pwsh --config "$env:POSH_THEMES_PATH/star.omp.json" | Invoke-Expression` manually, got no error. But nothing changed.

### Theme

star

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
PS>oh-my-posh debug

Version: 8.32.0

Segments:

ConsoleTitle(false) -   0 ms -
root(false) -   0 ms -
path(true)  -   0 ms - ~
git(false)  -   2 ms -
node(false) -   0 ms -
exit(false) -   0 ms -
text(true)  -   0 ms - ➜

Run duration: 11.3061ms

Cache path: C:\Users\kid14\AppData\Local\oh-my-posh

Config path: C:\Program Files (x86)\oh-my-posh\themes\star.omp.json

Logs:

2022/08/18 20:53:31 debug: Getenv
C:\Users\kid14\AppData\Local
2022/08/18 20:53:31 Getenv duration: 0s, args: LOCALAPPDATA
2022/08/18 20:53:31 CachePath duration: 0s, args:
2022/08/18 20:53:31 debug: Getenv
C:\Program Files (x86)\oh-my-posh\themes\star.omp.json
2022/08/18 20:53:31 Getenv duration: 0s, args: POSH_THEME
2022/08/18 20:53:31 Shell duration: 6.7252ms, args:
2022/08/18 20:53:31 resolveConfigPath duration: 6.7252ms, args:
2022/08/18 20:53:31 Init duration: 7.7721ms, args:
2022/08/18 20:53:31 Flags duration: 0s, args:
2022/08/18 20:53:31 config.loadConfig duration: 518.3µs, args:
2022/08/18 20:53:31 Flags duration: 0s, args:
2022/08/18 20:53:31 debug: Getenv

2022/08/18 20:53:31 Getenv duration: 0s, args: OMP_CACHE_DISABLED
2022/08/18 20:53:31 WindowsRegistryKeyValue duration: 0s, args: HKEY_CURRENT_USER\Software\Microsoft\Windows\DWM\ColorizationColor
2022/08/18 20:53:31 PathSeparator duration: 0s, args:
2022/08/18 20:53:31 PathSeparator duration: 0s, args:
2022/08/18 20:53:31 PathSeparator duration: 0s, args:
2022/08/18 20:53:31 PathSeparator duration: 0s, args:
2022/08/18 20:53:31 PathSeparator duration: 0s, args:
2022/08/18 20:53:31 PathSeparator duration: 0s, args:
2022/08/18 20:53:31 PathSeparator duration: 0s, args:
2022/08/18 20:53:31 PathSeparator duration: 0s, args:
2022/08/18 20:53:31 PathSeparator duration: 0s, args:
2022/08/18 20:53:31 PathSeparator duration: 0s, args:
2022/08/18 20:53:31 PathSeparator duration: 0s, args:
2022/08/18 20:53:31 PathSeparator duration: 0s, args:
2022/08/18 20:53:31 PathSeparator duration: 0s, args:
2022/08/18 20:53:31 PathSeparator duration: 0s, args:
2022/08/18 20:53:31 PathSeparator duration: 0s, args:
2022/08/18 20:53:31 PathSeparator duration: 0s, args:
2022/08/18 20:53:31 PathSeparator duration: 0s, args:
2022/08/18 20:53:31 PathSeparator duration: 0s, args:
2022/08/18 20:53:31 PathSeparator duration: 0s, args:
2022/08/18 20:53:31 debug: WindowsRegistryKeyValue
ColorizationColor(DWORD): 0xC40078D4
2022/08/18 20:53:31 Root duration: 432.9µs, args:
2022/08/18 20:53:31 Shell duration: 0s, args:
2022/08/18 20:53:31 ErrorCode duration: 0s, args:
2022/08/18 20:53:31 IsWsl duration: 0s, args:
2022/08/18 20:53:31 debug: Pwd
C:\Users\kid14
2022/08/18 20:53:31 Pwd duration: 0s, args:
2022/08/18 20:53:31 debug: Home
C:\Users\kid14
2022/08/18 20:53:31 PathSeparator duration: 0s, args:
2022/08/18 20:53:31 PathSeparator duration: 0s, args:
2022/08/18 20:53:31 debug: User
kid14
2022/08/18 20:53:31 User duration: 0s, args:
2022/08/18 20:53:31 debug: Host
win
2022/08/18 20:53:31 Host duration: 0s, args:
2022/08/18 20:53:31 GOOS duration: 0s, args:
2022/08/18 20:53:31 TemplateCache duration: 432.9µs, args:
2022/08/18 20:53:31 Flags duration: 0s, args:
2022/08/18 20:53:31 debug: Pwd
C:\Users\kid14
2022/08/18 20:53:31 Pwd duration: 0s, args:
2022/08/18 20:53:31 debug: Home
C:\Users\kid14
2022/08/18 20:53:31 GOOS duration: 0s, args:
2022/08/18 20:53:31 Root duration: 0s, args:
2022/08/18 20:53:31 debug: Pwd
C:\Users\kid14
2022/08/18 20:53:31 Pwd duration: 0s, args:
2022/08/18 20:53:31 debug: Home
C:\Users\kid14
2022/08/18 20:53:31 GOOS duration: 0s, args:
2022/08/18 20:53:31 debug: Pwd
C:\Users\kid14
2022/08/18 20:53:31 Pwd duration: 0s, args:
2022/08/18 20:53:31 Flags duration: 0s, args:
2022/08/18 20:53:31 debug: Pwd
C:\Users\kid14
2022/08/18 20:53:31 Pwd duration: 0s, args:
2022/08/18 20:53:31 debug: Home
C:\Users\kid14
2022/08/18 20:53:31 GOOS duration: 0s, args:
2022/08/18 20:53:31 GOOS duration: 0s, args:
2022/08/18 20:53:31 PathSeparator duration: 0s, args:
2022/08/18 20:53:31 PathSeparator duration: 0s, args:
2022/08/18 20:53:31 PathSeparator duration: 0s, args:
2022/08/18 20:53:31 PathSeparator duration: 0s, args:
2022/08/18 20:53:31 GOOS duration: 0s, args:
2022/08/18 20:53:31 IsWsl duration: 0s, args:
2022/08/18 20:53:31 StackCount duration: 0s, args:
2022/08/18 20:53:31 DirIsWritable duration: 0s, args:
2022/08/18 20:53:31 TemplateCache duration: 0s, args:
2022/08/18 20:53:31 TemplateCache duration: 0s, args:
2022/08/18 20:53:31 Shell duration: 0s, args:
2022/08/18 20:53:31 debug: Pwd
C:\Users\kid14
2022/08/18 20:53:31 Pwd duration: 0s, args:
2022/08/18 20:53:31 debug: Home
C:\Users\kid14
2022/08/18 20:53:31 GOOS duration: 0s, args:
2022/08/18 20:53:31 GOOS duration: 0s, args:
2022/08/18 20:53:31 debug: CommandPath
C:\Program Files\Git\cmd\git.exe
2022/08/18 20:53:31 CommandPath duration: 2.0621ms, args: git.exe
2022/08/18 20:53:31 HasCommand duration: 2.0621ms, args: git.exe
2022/08/18 20:53:31 debug: Pwd
C:\Users\kid14
2022/08/18 20:53:31 Pwd duration: 0s, args:
2022/08/18 20:53:31 error: HasParentFilePath
CreateFile C:\.git: The system cannot find the file specified.
2022/08/18 20:53:31 HasParentFilePath duration: 0s, args: .git
2022/08/18 20:53:31 debug: Pwd
C:\Users\kid14
2022/08/18 20:53:31 Pwd duration: 0s, args:
2022/08/18 20:53:31 debug: Home
C:\Users\kid14
2022/08/18 20:53:31 GOOS duration: 0s, args:
2022/08/18 20:53:31 debug: Pwd
C:\Users\kid14
2022/08/18 20:53:31 Pwd duration: 0s, args:
2022/08/18 20:53:31 debug: Home
C:\Users\kid14
2022/08/18 20:53:31 debug: Pwd
C:\Users\kid14
2022/08/18 20:53:31 Pwd duration: 0s, args:
2022/08/18 20:53:31 debug: Home
C:\Users\kid14
2022/08/18 20:53:31 GOOS duration: 0s, args:
2022/08/18 20:53:31 ErrorCode duration: 0s, args:
2022/08/18 20:53:31 ErrorCode duration: 0s, args:
2022/08/18 20:53:31 Flags duration: 0s, args:
2022/08/18 20:53:31 debug: Pwd
C:\Users\kid14
2022/08/18 20:53:31 Pwd duration: 0s, args:
2022/08/18 20:53:31 debug: Home
C:\Users\kid14
2022/08/18 20:53:31 GOOS duration: 0s, args:
2022/08/18 20:53:31 TemplateCache duration: 0s, args:
2022/08/18 20:53:31 TemplateCache duration: 0s, args:
2022/08/18 20:53:31 Shell duration: 0s, args:
2022/08/18 20:53:31 debug: Getenv
C:\Users\kid14\AppData\Local
2022/08/18 20:53:31 Getenv duration: 0s, args: LOCALAPPDATA
2022/08/18 20:53:31 CachePath duration: 511.4µs, args:
2022/08/18 20:53:31 Flags duration: 0s, args:
```

**Comment by JanDeDobbeleer** [comment]
@kid1412621 what does the $error variable say?

**Comment by kid1412621** [comment]
```log
Get-GitStatus:
Line |
  99 |              $global:GitStatus = Get-GitStatus
     |                                  ~~~~~~~~~~~~~
     | The term 'Get-GitStatus' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
ErrorRecord                 : The term 'Get-GitStatus' is not recognized as a name of a cmdlet, function, script file, or executable program.
                              Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
CommandName                 : Get-GitStatus
WasThrownFromThrowStatement : False
TargetSite                  : System.Collections.ObjectModel.Collection`1[System.Management.Automation.PSObject] Invoke(System.Collections.IEnumerable)
Message                     : The term 'Get-GitStatus' is not recognized as a name of a cmdlet, function, script file, or executable program.
                              Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
Data                        : {System.Management.Automation.Interpreter.InterpretedFrameInfo}
InnerException              :
HelpLink                    :
Source                      : System.Management.Automation
HResult                     : -2146233087
StackTrace                  :    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
                                 at System.Management.Automation.Runspaces.Pipeline.Invoke()
                                 at Microsoft.PowerShell.Executor.ExecuteCommandHelper(Pipeline tempPipeline, Exception& exceptionThrown, ExecutionOptions options)
```

**Comment by lewis-yeung** [comment]
@kid1412621 You don't have [posh-git](https://github.com/dahlbyk/posh-git) imported, do you? I bet it will work if you comment out the `$env:POSH_GIT_ENABLED = $true` line.

**Comment by kid1412621** [comment]
thank you all!!! If any detailed error provided will be nice to troubleshoot.

**Comment by JanDeDobbeleer** [comment]
@kid1412621 that's a PowerShell issue, thankfully they have proper error handling. We initially did validate the module availability but that takes too much time so we decided to use the environment variable.

@lewis-yeung maybe it's an idea to check the module's presence on init and use a script boolean?

**Comment by lewis-yeung** [comment]
@JanDeDobbeleer Should we add a check like `$null -ne (Get-Command 'Get-GitStatus' -ErrorAction Ignore)`?

**Comment by JanDeDobbeleer** [comment]
@lewis-yeung I think the history should show the command we used, could be the same. I can check later today. But if this one works, all fine.

The thing is, do we want to force it being enabled without user consent as it will fetch git status twice every time if the user also uses the git segment. So maybe we add this additionally and avoid the prompt failing like in this issue, but still use the environment variable to enable it explicitly.

**Comment by lewis-yeung** [comment]
> So maybe we add this additionally and avoid the prompt failing like in this issue, but still use the environment variable to enable it explicitly.

@JanDeDobbeleer Agreed. I think we can use `Get-Module` and tweak the check like:

```powershell
if (($null -eq $env:POSH_GIT_ENABLED) -or ($null -eq (Get-Module 'posh-git'))) {
    $env:POSH_GIT_ENABLED = $false
}
```

which will reset `$env:POSH_GIT_ENABLED` to `$false` if the "posh-git" module is not imported.
