### ISSUE TITLE
panic on font install 

### ISSUE THREAD

**Issue by webstean** [JanDeDobbeleer/oh-my-posh#2690]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

PS C:\Users\andreww> oh-my-posh font install CascadiaCode

    🌎 Downloading https://github.com/ryanoasis/nerd-fonts/releases/latest/download/CascadiaCode.zip

Caught panic:

runtime error: invalid memory address or nil pointer dereference

Restoring terminal...

goroutine 1 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.18.4/x64/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        /opt/hostedtoolcache/go/1.18.4/x64/src/runtime/debug/stack.go:16 +0x19
github.com/charmbracelet/bubbletea.(*Program).StartReturningModel.func3()
        /home/runner/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.22.0/tea.go:371 +0x95
panic({0x14ff540, 0x2088590})
        /opt/hostedtoolcache/go/1.18.4/x64/src/runtime/panic.go:844 +0x258
oh-my-posh/font.(*main).Update(0xc00013ee00, {0x1552b00?, 0xc00040a4b0?})
        /home/runner/work/oh-my-posh/oh-my-posh/src/font/cli.go:171 +0x281
github.com/charmbracelet/bubbletea.(*Program).StartReturningModel(0xc0000f68f0)
        /home/runner/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.22.0/tea.go:540 +0x1291
github.com/charmbracelet/bubbletea.(*Program).Start(...)
        /home/runner/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.22.0/tea.go:549
oh-my-posh/font.Run({0xc0000aa0a0, 0xc})
        /home/runner/work/oh-my-posh/oh-my-posh/src/font/cli.go:239 +0x94
oh-my-posh/cli.glob..func7(0x2094840?, {0xc0000a5ae0?, 0x2?, 0x2?})
        /home/runner/work/oh-my-posh/oh-my-posh/src/cli/font.go:35 +0x7f
github.com/spf13/cobra.(*Command).execute(0x2094840, {0xc0000a5a80, 0x2, 0x2})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x67b
github.com/spf13/cobra.(*Command).ExecuteC(0x2094340)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
oh-my-posh/cli.Execute({0x16f8254?, 0xc000062000?})
        /home/runner/work/oh-my-posh/oh-my-posh/src/cli/root.go:40 +0x4a
main.main()
        /home/runner/work/oh-my-posh/oh-my-posh/src/main.go:10 +0x27

### Theme

n/a

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
PS C:\Users\andreww> oh-my-posh debug

Version: 8.29.5

Segments:

ConsoleTitle(true) -   2 ms - pwsh in ~
session(true)  -   3 ms -  andreww 
path(true)     -   1 ms -   ~
git(false)     -  11 ms -
root(true)     -   0 ms -  
exit(true)     -   0 ms -   
node(false)    -   0 ms -
go(false)      -   0 ms -
python(false)  -   0 ms -
shell(true)    -   5 ms - in pwsh
time(true)     -   0 ms - at 23:25:54

Run duration: 206.5478ms

Cache path: C:\Users\andreww\AppData\Local\oh-my-posh

Config path: C:\Users\andreww\AppData\Local\oh-my-posh\config.omp.json

Logs:

2022/08/22 23:25:54 debug: Getenv
C:\Users\andreww\AppData\Local
2022/08/22 23:25:54 Getenv duration: 553µs, args: LOCALAPPDATA
2022/08/22 23:25:54 CachePath duration: 1.7617ms, args:
2022/08/22 23:25:54 debug: Getenv

2022/08/22 23:25:54 Getenv duration: 0s, args: POSH_THEME
2022/08/22 23:25:54 debug: Getenv
C:\Users\andreww\AppData\Local
2022/08/22 23:25:54 Getenv duration: 0s, args: LOCALAPPDATA
2022/08/22 23:25:54 CachePath duration: 206.6µs, args:
2022/08/22 23:25:54 debug: HTTPRequest
GET /JanDeDobbeleer/oh-my-posh/v8.29.5/themes/default.omp.json HTTP/1.1
Host: raw.githubusercontent.com
User-Agent: Go-http-client/1.1
Accept-Encoding: gzip


2022/08/22 23:25:54 debug: HTTPRequest
{
  "$schema": "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json",
  "blocks": [
    {
      "alignment": "left",
      "segments": [
        {
          "background": "p:yellow",
          "foreground": "p:black",
          "leading_diamond": "\ue0b6",
          "properties": {
            "display_host": false
          },
          "style": "diamond",
          "template": " {{ if .SSHSession }}\uf817 {{ end }}{{ .UserName }} ",
          "trailing_diamond": "\ue0b0",
          "type": "session"
        },
        {
          "background": "p:orange",
          "foreground": "p:white",
          "powerline_symbol": "\ue0b0",
          "properties": {
            "home_icon": "~",
            "style": "folder"
          },
          "style": "powerline",
          "template": " \uf74a {{ path .Path .Location }} ",
          "type": "path"
        },
        {
          "background": "p:green",
          "background_templates": [
            "{{ if or (.Working.Changed) (.Staging.Changed) }}p:yellow{{ end }}",
            "{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:red{{ end }}",
            "{{ if gt .Ahead 0 }}#49416D{{ end }}",
            "{{ if gt .Behind 0 }}#7A306C{{ end }}"
          ],
          "foreground": "p:black",
          "foreground_templates": [
            "{{ if or (.Working.Changed) (.Staging.Changed) }}p:black{{ end }}",
            "{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:white{{ end }}",
            "{{ if gt .Ahead 0 }}p:white{{ end }}"
          ],
          "powerline_symbol": "\ue0b0",
          "properties": {
            "branch_max_length": 25,
            "fetch_status": true,
            "fetch_upstream_icon": true,
            "github_icon": "\uf7a3"
          },
          "style": "powerline",
          "template": " {{ if .UpstreamURL }}{{ url .UpstreamIcon .UpstreamURL }} {{ end }}{{ .HEAD }}{{ .BranchStatus }}{{ if .Working.Changed }} \uf044 {{ .Working.String }}{{ end }}{{ if .Staging.Changed }} \uf046 {{ .Staging.String }}{{ end }} ",
          "type": "git"
        },
        {
          "background": "p:yellow",
          "foreground": "p:white",
          "powerline_symbol": "\ue0b0",
          "properties": {
            "root_icon": "\uf0ad"
          },
          "style": "powerline",
          "template": " \uf0e7 ",
          "type": "root"
        },
        {
          "background": "p:blue",
          "background_templates": [
            "{{ if gt .Code 0 }}p:red{{ end }}"
          ],
          "foreground": "p:white",
          "leading_diamond": "<transparent,background>\ue0b0</>",
          "properties": {
            "always_enabled": true
          },
          "style": "diamond",
          "template": " {{ if gt .Code 0 }}\uf00d{{ else }}\uf00c{{ end }} ",
          "trailing_diamond": "\ue0b4",
          "type": "exit"
        }
      ],
      "type": "prompt"
    },
    {
      "segments": [
        {
          "background": "transparent",
          "foreground": "p:green",
          "properties": {
            "display_mode": "files",
            "fetch_package_manager": false,
            "home_enabled": false
          },
          "style": "plain",
          "template": "\uf898 ",
          "type": "node"
        },
        {
          "background": "transparent",
          "foreground": "p:blue",
          "properties": {
            "fetch_version": false
          },
          "style": "powerline",
          "template": "\ufcd1 ",
          "type": "go"
        },
        {
          "background": "transparent",
          "foreground": "p:yellow",
          "properties": {
            "display_mode": "files",
            "fetch_version": true,
            "fetch_virtual_env": false
          },
          "style": "plain",
          "template": "\ue235 ",
          "type": "python"
        },
        {
          "background": "transparent",
          "foreground": "p:white",
          "style": "plain",
          "template": "in <p:blue><b>{{ .Name }}</b></> ",
          "type": "shell"
        },
        {
          "background": "transparent",
          "foreground": "p:white",
          "style": "plain",
          "template": "at <p:blue><b>{{ .CurrentDate | date \"15:04:05\" }}</b></>",
          "type": "time"
        }
      ],
      "type": "rprompt"
    }
  ],
  "console_title_template": "{{ .Shell }} in {{ .Folder }}",
  "final_space": true,
  "palette": {
    "black": "#262B44",
    "blue": "#4B95E9",
    "green": "#59C9A5",
    "orange": "#F07623",
    "red": "#D81E5B",
    "white": "#E0DEF4",
    "yellow": "#F3AE35"
  },
  "secondary_prompt": {
    "background": "transparent",
    "foreground": "p:black",
    "template": "<p:yellow,transparent>\ue0b6</><,p:yellow> > </><p:yellow,transparent>\ue0b0</> "
  },
  "tooltips": [
    {
      "background": "p:orange",
      "foreground": "p:white",
      "leading_diamond": "\ue0b6",
      "properties": {
        "display_default": true
      },
      "style": "diamond",
      "template": " \ue7ad {{ .Profile }}{{ if .Region }}@{{ .Region }}{{ end }} ",
      "tips": [
        "aws"
      ],
      "trailing_diamond": "\ue0b4",
      "type": "aws"
    },
    {
      "background": "p:blue",
      "foreground": "p:white",
      "leading_diamond": "\ue0b6",
      "style": "diamond",
      "template": " \ufd03 {{ .Name }} ",
      "tips": [
        "az"
      ],
      "trailing_diamond": "\ue0b4",
      "type": "az"
    }
  ],
  "transient_prompt": {
    "background": "transparent",
    "foreground": "p:black",
    "template": "<p:yellow,transparent>\ue0b6</><,p:yellow> {{ .Folder }} </><p:yellow,transparent>\ue0b0</> "
  },
  "version": 2
}

2022/08/22 23:25:54 HTTPRequest duration: 95.1644ms, args: https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/v8.29.5/themes/default.omp.json
2022/08/22 23:25:54 downloadConfig duration: 113.2384ms, args: https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/v8.29.5/themes/default.omp.json
2022/08/22 23:25:54 Shell duration: 13.1648ms, args:
2022/08/22 23:25:54 resolveConfigPath duration: 127.4101ms, args:
2022/08/22 23:25:54 Init duration: 168.1347ms, args:
2022/08/22 23:25:54 Flags duration: 0s, args:
2022/08/22 23:25:54 config.loadConfig duration: 11.1334ms, args:
2022/08/22 23:25:54 Flags duration: 0s, args:
2022/08/22 23:25:54 debug: Getenv

2022/08/22 23:25:54 Getenv duration: 0s, args: OMP_CACHE_DISABLED
2022/08/22 23:25:54 WindowsRegistryKeyValue duration: 0s, args: HKEY_CURRENT_USER\Software\Microsoft\Windows\DWM\ColorizationColor
2022/08/22 23:25:54 PathSeparator duration: 0s, args:
2022/08/22 23:25:54 PathSeparator duration: 0s, args:
2022/08/22 23:25:54 PathSeparator duration: 0s, args:
2022/08/22 23:25:54 PathSeparator duration: 0s, args:
2022/08/22 23:25:54 PathSeparator duration: 0s, args:
2022/08/22 23:25:54 PathSeparator duration: 0s, args:
2022/08/22 23:25:54 PathSeparator duration: 0s, args:
2022/08/22 23:25:54 PathSeparator duration: 0s, args:
2022/08/22 23:25:54 PathSeparator duration: 0s, args:
2022/08/22 23:25:54 PathSeparator duration: 0s, args:
2022/08/22 23:25:54 PathSeparator duration: 0s, args:
2022/08/22 23:25:54 PathSeparator duration: 0s, args:
2022/08/22 23:25:54 PathSeparator duration: 0s, args:
2022/08/22 23:25:54 PathSeparator duration: 0s, args:
2022/08/22 23:25:54 PathSeparator duration: 0s, args:
2022/08/22 23:25:54 PathSeparator duration: 0s, args:
2022/08/22 23:25:54 PathSeparator duration: 0s, args:
2022/08/22 23:25:54 PathSeparator duration: 0s, args:
2022/08/22 23:25:54 PathSeparator duration: 0s, args:
2022/08/22 23:25:54 debug: WindowsRegistryKeyValue
ColorizationColor(DWORD): 0xC42165B8
2022/08/22 23:25:54 Root duration: 60.9µs, args:
2022/08/22 23:25:54 Shell duration: 0s, args:
2022/08/22 23:25:54 ErrorCode duration: 0s, args:
2022/08/22 23:25:54 IsWsl duration: 0s, args:
2022/08/22 23:25:54 debug: Pwd
C:\Users\andreww
2022/08/22 23:25:54 Pwd duration: 0s, args:
2022/08/22 23:25:54 debug: Home
C:\Users\andreww
2022/08/22 23:25:54 PathSeparator duration: 0s, args:
2022/08/22 23:25:54 PathSeparator duration: 0s, args:
2022/08/22 23:25:54 debug: User
andreww
2022/08/22 23:25:54 User duration: 0s, args:
2022/08/22 23:25:54 debug: Host
ANDREW-SURFACE
2022/08/22 23:25:54 Host duration: 503.1µs, args:
2022/08/22 23:25:54 GOOS duration: 0s, args:
2022/08/22 23:25:54 TemplateCache duration: 564µs, args:
2022/08/22 23:25:54 Flags duration: 0s, args:
2022/08/22 23:25:54 debug: Pwd
C:\Users\andreww
2022/08/22 23:25:54 Pwd duration: 0s, args:
2022/08/22 23:25:54 debug: Home
C:\Users\andreww
2022/08/22 23:25:54 GOOS duration: 0s, args:
2022/08/22 23:25:54 debug: Getenv

2022/08/22 23:25:54 Getenv duration: 0s, args: SSH_CONNECTION
2022/08/22 23:25:54 debug: Getenv

2022/08/22 23:25:54 Getenv duration: 0s, args: SSH_CLIENT
2022/08/22 23:25:54 TemplateCache duration: 0s, args:
2022/08/22 23:25:54 TemplateCache duration: 0s, args:
2022/08/22 23:25:54 Shell duration: 0s, args:
2022/08/22 23:25:54 debug: Pwd
C:\Users\andreww
2022/08/22 23:25:54 Pwd duration: 0s, args:
2022/08/22 23:25:54 debug: Home
C:\Users\andreww
2022/08/22 23:25:54 GOOS duration: 0s, args:
2022/08/22 23:25:54 debug: Pwd
C:\Users\andreww
2022/08/22 23:25:54 Pwd duration: 0s, args:
2022/08/22 23:25:54 Flags duration: 0s, args:
2022/08/22 23:25:54 debug: Pwd
C:\Users\andreww
2022/08/22 23:25:54 Pwd duration: 0s, args:
2022/08/22 23:25:54 debug: Home
C:\Users\andreww
2022/08/22 23:25:54 GOOS duration: 0s, args:
2022/08/22 23:25:54 GOOS duration: 0s, args:
2022/08/22 23:25:54 PathSeparator duration: 0s, args:
2022/08/22 23:25:54 PathSeparator duration: 0s, args:
2022/08/22 23:25:54 PathSeparator duration: 0s, args:
2022/08/22 23:25:54 PathSeparator duration: 0s, args:
2022/08/22 23:25:54 GOOS duration: 0s, args:
2022/08/22 23:25:54 IsWsl duration: 0s, args:
2022/08/22 23:25:54 StackCount duration: 0s, args:
2022/08/22 23:25:54 DirIsWritable duration: 545.6µs, args:
2022/08/22 23:25:54 TemplateCache duration: 0s, args:
2022/08/22 23:25:54 TemplateCache duration: 0s, args:
2022/08/22 23:25:54 Shell duration: 0s, args:
2022/08/22 23:25:54 debug: Pwd
C:\Users\andreww
2022/08/22 23:25:54 Pwd duration: 0s, args:
2022/08/22 23:25:54 debug: Home
C:\Users\andreww
2022/08/22 23:25:54 GOOS duration: 0s, args:
2022/08/22 23:25:54 GOOS duration: 0s, args:
2022/08/22 23:25:54 debug: CommandPath
C:\Program Files\Git\cmd\git.exe
2022/08/22 23:25:54 CommandPath duration: 10.7475ms, args: git.exe
2022/08/22 23:25:54 HasCommand duration: 10.7475ms, args: git.exe
2022/08/22 23:25:54 debug: Pwd
C:\Users\andreww
2022/08/22 23:25:54 Pwd duration: 0s, args:
2022/08/22 23:25:54 error: HasParentFilePath
CreateFile C:\.git: The system cannot find the file specified.
2022/08/22 23:25:54 HasParentFilePath duration: 0s, args: .git
2022/08/22 23:25:54 debug: Pwd
C:\Users\andreww
2022/08/22 23:25:54 Pwd duration: 0s, args:
2022/08/22 23:25:54 debug: Home
C:\Users\andreww
2022/08/22 23:25:54 GOOS duration: 0s, args:
2022/08/22 23:25:54 Root duration: 0s, args:
2022/08/22 23:25:54 TemplateCache duration: 0s, args:
2022/08/22 23:25:54 TemplateCache duration: 0s, args:
2022/08/22 23:25:54 Shell duration: 0s, args:
2022/08/22 23:25:54 debug: Pwd
C:\Users\andreww
2022/08/22 23:25:54 Pwd duration: 0s, args:
2022/08/22 23:25:54 debug: Home
C:\Users\andreww
2022/08/22 23:25:54 GOOS duration: 0s, args:
2022/08/22 23:25:54 ErrorCode duration: 0s, args:
2022/08/22 23:25:54 TemplateCache duration: 0s, args:
2022/08/22 23:25:54 TemplateCache duration: 0s, args:
2022/08/22 23:25:54 Shell duration: 0s, args:
2022/08/22 23:25:54 TemplateCache duration: 0s, args:
2022/08/22 23:25:54 Flags duration: 0s, args:
2022/08/22 23:25:54 debug: Pwd
C:\Users\andreww
2022/08/22 23:25:54 Pwd duration: 0s, args:
2022/08/22 23:25:54 debug: Home
C:\Users\andreww
2022/08/22 23:25:54 GOOS duration: 0s, args:
2022/08/22 23:25:54 debug: Pwd
C:\Users\andreww
2022/08/22 23:25:54 Pwd duration: 0s, args:
2022/08/22 23:25:54 debug: Home
C:\Users\andreww
2022/08/22 23:25:54 debug: Pwd
C:\Users\andreww
2022/08/22 23:25:54 Pwd duration: 0s, args:
2022/08/22 23:25:54 debug: Home
C:\Users\andreww
2022/08/22 23:25:54 GOOS duration: 0s, args:
2022/08/22 23:25:54 debug: Pwd
C:\Users\andreww
2022/08/22 23:25:54 Pwd duration: 0s, args:
2022/08/22 23:25:54 debug: Home
C:\Users\andreww
2022/08/22 23:25:54 debug: Pwd
C:\Users\andreww
2022/08/22 23:25:54 Pwd duration: 0s, args:
2022/08/22 23:25:54 debug: Home
C:\Users\andreww
2022/08/22 23:25:54 GOOS duration: 0s, args:
2022/08/22 23:25:54 debug: Pwd
C:\Users\andreww
2022/08/22 23:25:54 Pwd duration: 0s, args:
2022/08/22 23:25:54 debug: Home
C:\Users\andreww
2022/08/22 23:25:54 debug: Pwd
C:\Users\andreww
2022/08/22 23:25:54 Pwd duration: 0s, args:
2022/08/22 23:25:54 PathSeparator duration: 0s, args:
2022/08/22 23:25:54 debug: HasFiles
false
2022/08/22 23:25:54 HasFiles duration: 0s, args: *.py
2022/08/22 23:25:54 debug: Pwd
C:\Users\andreww
2022/08/22 23:25:54 Pwd duration: 0s, args:
2022/08/22 23:25:54 PathSeparator duration: 0s, args:
2022/08/22 23:25:54 debug: HasFiles
false
2022/08/22 23:25:54 HasFiles duration: 0s, args: *.ipynb
2022/08/22 23:25:54 debug: Pwd
C:\Users\andreww
2022/08/22 23:25:54 Pwd duration: 0s, args:
2022/08/22 23:25:54 PathSeparator duration: 0s, args:
2022/08/22 23:25:54 debug: HasFiles
false
2022/08/22 23:25:54 HasFiles duration: 0s, args: pyproject.toml
2022/08/22 23:25:54 debug: Pwd
C:\Users\andreww
2022/08/22 23:25:54 Pwd duration: 0s, args:
2022/08/22 23:25:54 PathSeparator duration: 0s, args:
2022/08/22 23:25:54 debug: HasFiles
false
2022/08/22 23:25:54 HasFiles duration: 0s, args: venv.bak
2022/08/22 23:25:54 debug: HasFolder
false
2022/08/22 23:25:54 HasFolder duration: 0s, args: .venv
2022/08/22 23:25:54 debug: HasFolder
false
2022/08/22 23:25:54 HasFolder duration: 0s, args: venv
2022/08/22 23:25:54 debug: HasFolder
false
2022/08/22 23:25:54 HasFolder duration: 0s, args: virtualenv
2022/08/22 23:25:54 debug: HasFolder
false
2022/08/22 23:25:54 HasFolder duration: 0s, args: env
2022/08/22 23:25:54 debug: HasFolder
false
2022/08/22 23:25:54 HasFolder duration: 0s, args: venv-win
2022/08/22 23:25:54 debug: HasFolder
false
2022/08/22 23:25:54 HasFolder duration: 0s, args: pyenv-win
2022/08/22 23:25:54 debug: Pwd
C:\Users\andreww
2022/08/22 23:25:54 Pwd duration: 0s, args:
2022/08/22 23:25:54 debug: Home
C:\Users\andreww
2022/08/22 23:25:54 GOOS duration: 0s, args:
2022/08/22 23:25:54 Shell duration: 0s, args:
2022/08/22 23:25:54 Flags duration: 0s, args:
2022/08/22 23:25:54 TemplateCache duration: 0s, args:
2022/08/22 23:25:54 TemplateCache duration: 0s, args:
2022/08/22 23:25:54 Shell duration: 0s, args:
2022/08/22 23:25:54 debug: Pwd
C:\Users\andreww
2022/08/22 23:25:54 Pwd duration: 0s, args:
2022/08/22 23:25:54 debug: Home
C:\Users\andreww
2022/08/22 23:25:54 GOOS duration: 0s, args:
2022/08/22 23:25:54 TemplateCache duration: 0s, args:
2022/08/22 23:25:54 TemplateCache duration: 0s, args:
2022/08/22 23:25:54 Shell duration: 0s, args:
2022/08/22 23:25:54 debug: Getenv
C:\Users\andreww\AppData\Local
2022/08/22 23:25:54 Getenv duration: 0s, args: LOCALAPPDATA
2022/08/22 23:25:54 CachePath duration: 0s, args:
2022/08/22 23:25:54 Flags duration: 0s, args:
```

**Comment by JanDeDobbeleer** [comment]
@webstean I'm following up on this in #2338, so I'm closing this one and will provide updates there as soon as I'm back from my holidays.

**Comment by JanDeDobbeleer** [comment]
@webstean btw, I don't think Cascadia Code exists as a nerd fort. Try oh-my-posh font install and select the right font.

**Comment by lewis-yeung** [comment]
> btw, I don't think Cascadia Code exists as a nerd fort.

@JanDeDobbeleer It does exist. `CascadiaCode` is in the list output by `oh-my-posh font install`, and `https://github.com/ryanoasis/nerd-fonts/releases/latest/download/CascadiaCode.zip` is an valid download URL.

**Comment by JanDeDobbeleer** [comment]
@lewis-yeung this whole functionality is on my todo list anyways. Will have a proper look once I'm back.

**Comment by JanDeDobbeleer** [comment]
@webstean I know why this happens, you pressed enter multiple times. If you enter the command, press enter and wait, it runs successfully. BUT, if you press enter twice (or during the download), it crashes.

**Comment by webstean** [comment]
Nice :-) It also fails unless you are in admin terminal - would be nice if it prompted to start an admin terminal
Also, would be even better if there was an option to edit the VS Code settings.json as well :-)

**Comment by JanDeDobbeleer** [comment]
@webstean the first one is possible, the second one isn't one I'm planning on maintaining. The reason is that this is simply too hard to maintain as settings change etc.

**Comment by webstean** [comment]
Source: https://docs.microsoft.com/en-us/windows/terminal/install#settings-json-file
Terminal (stable / general release):
%LOCALAPPDATA%\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\settings.json
Terminal (preview release): %LOCALAPPDATA%\Packages\Microsoft.WindowsTerminalPreview_8wekyb3d8bbwe\LocalState\settings.json
are dumb filenames for sure.
And it seems unlikely the actual setting for Font Face would change.
If you were prepared to add it, I'd be happy to maintain it

**Comment by JanDeDobbeleer** [comment]
@webstean what I don't know is if we can simply (and reliably) swap one key's value in the json without ruining other settings. That's why I'm not inclined to even pursue this.
