### ISSUE TITLE
Prompt does not return/render when current directory does not exists

### ISSUE THREAD

**Issue by CodexLink** [JanDeDobbeleer/oh-my-posh#2873]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

## Info

Whenever a prompt's currently set directory is a **previously-existing folder**, the prompt won't render itself but rather stay on the stock prompt until it goes below the directory where a folder exists. It is also shown that it double-enters _(where two PS shows up after pressing ENTER key manually)_ the prompt, but I'm not quite sure if that's because of the theme.

This bug may impact people who usually work on various branches where folders show up from one another.

## PowerShell Log
Please note that, as much as I wanted to provide specific logs, the `oh-my-posh debug` cannot produce an output (_as part of why I didn't put this log in the Log output section_), **however** I was able to catch the excerpt of my PowerShell logs.

```text
Exception calling "Start" with "0" argument(s): "An error occurred trying to start process 'C:/Users/janja/scoop/apps/oh-my-posh/current/bin/oh-my-posh.exe' with working directory 'C:\Users\janja\Desktop\trigger-test\test-folder'. The directory name is invalid."
You cannot call a method on a null-valued expression.
You cannot call a method on a null-valued expression.
Exception calling "WaitForExit" with "0" argument(s): "No process is associated with this object."
You cannot call a method on a null-valued expression.
Exception calling "Start" with "0" argument(s): "An error occurred trying to start process 'C:/Users/janja/scoop/apps/oh-my-posh/current/bin/oh-my-posh.exe' with working directory 'C:\Users\janja\Desktop\trigger-test\test-folder'. The directory name is invalid."
Exception calling "Start" with "0" argument(s): "An error occurred trying to start process 'C:/Users/janja/scoop/apps/oh-my-posh/current/bin/oh-my-posh.exe' with working directory 'C:\Users\janja\Desktop\trigger-test\test-folder'. The directory name is invalid."
You cannot call a method on a null-valued expression.
You cannot call a method on a null-valued expression.
Exception calling "WaitForExit" with "0" argument(s): "No process is associated with this object."
You cannot call a method on a null-valued expression.
Exception calling "Start" with "0" argument(s): "An error occurred trying to start process 'C:/Users/janja/scoop/apps/oh-my-posh/current/bin/oh-my-posh.exe' with working directory 'C:\Users\janja\Desktop\trigger-test\test-folder'. The directory name is invalid."
Exception calling "Start" with "0" argument(s): "An error occurred trying to start process 'C:/Users/janja/scoop/apps/oh-my-posh/current/bin/oh-my-posh.exe' with working directory 'C:\Users\janja\Desktop\trigger-test\test-folder'. The directory name is invalid."
You cannot call a method on a null-valued expression.
You cannot call a method on a null-valued expression.
Exception calling "WaitForExit" with "0" argument(s): "No process is associated with this object."
You cannot call a method on a null-valued expression.
```

## PowerShell Log (Raw from Console)
> Produced with the command: `$Error`
```
InvalidOperation:
Line |
  94 |          $stderr = $stderrTask.Result.Trim()
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.

MethodInvocationException:
Line |
  93 |          $Process.WaitForExit()
     |          ~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "WaitForExit" with "0" argument(s): "No process is associated with this object."

InvalidOperation:
Line |
  92 |          $stderrTask = $Process.StandardError.ReadToEndAsync()
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.

InvalidOperation:
Line |
  91 |          $stdoutTask = $Process.StandardOutput.ReadToEndAsync()
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.

MethodInvocationException:
Line |
  89 |          [void]$Process.Start()
     |          ~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "Start" with "0" argument(s): "An error occurred trying to start process 'C:/Users/janja/scoop/apps/oh-my-posh/current/bin/oh-my-posh.exe' with working directory 'C:\Users\janja\Desktop\trigger-test\test-folder'. The directory name is invalid."

ErrorRecord                 : Exception calling "Start" with "0" argument(s): "An error occurred trying to start
                              process 'C:/Users/janja/scoop/apps/oh-my-posh/current/bin/oh-my-posh.exe' with working
                              directory 'C:\Users\janja\Desktop\trigger-test\test-folder'. The directory name is
                              invalid."
WasThrownFromThrowStatement : False
TargetSite                  : System.Collections.ObjectModel.Collection`1[System.Management.Automation.PSObject]
                              Invoke(System.Collections.IEnumerable)
Message                     : Exception calling "Start" with "0" argument(s): "An error occurred trying to start
                              process 'C:/Users/janja/scoop/apps/oh-my-posh/current/bin/oh-my-posh.exe' with working
                              directory 'C:\Users\janja\Desktop\trigger-test\test-folder'. The directory name is
                              invalid."
Data                        : {System.Management.Automation.Interpreter.InterpretedFrameInfo}
InnerException              : System.ComponentModel.Win32Exception (267): An error occurred trying to start process
                              'C:/Users/janja/scoop/apps/oh-my-posh/current/bin/oh-my-posh.exe' with working directory
                              'C:\Users\janja\Desktop\trigger-test\test-folder'. The directory name is invalid.
                                 at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
                                 at System.Diagnostics.Process.Start()
                                 at CallSite.Target(Closure , CallSite , Object )
HelpLink                    :
Source                      : System.Management.Automation
HResult                     : -2146233087
StackTrace                  :    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
                                 at System.Management.Automation.Runspaces.Pipeline.Invoke()
                                 at Microsoft.PowerShell.Executor.ExecuteCommandHelper(Pipeline tempPipeline,
                              Exception& exceptionThrown, ExecutionOptions options)


MethodInvocationException:
Line |
  89 |          [void]$Process.Start()
     |          ~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "Start" with "0" argument(s): "An error occurred trying to start process 'C:/Users/janja/scoop/apps/oh-my-posh/current/bin/oh-my-posh.exe' with working directory 'C:\Users\janja\Desktop\trigger-test\test-folder'. The directory name is invalid."

InvalidOperation:
Line |
  94 |          $stderr = $stderrTask.Result.Trim()
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.

MethodInvocationException:
Line |
  93 |          $Process.WaitForExit()
     |          ~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "WaitForExit" with "0" argument(s): "No process is associated with this object."

InvalidOperation:
Line |
  92 |          $stderrTask = $Process.StandardError.ReadToEndAsync()
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.

InvalidOperation:
Line |
  91 |          $stdoutTask = $Process.StandardOutput.ReadToEndAsync()
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.

MethodInvocationException:
Line |
  89 |          [void]$Process.Start()
     |          ~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "Start" with "0" argument(s): "An error occurred trying to start process 'C:/Users/janja/scoop/apps/oh-my-posh/current/bin/oh-my-posh.exe' with working directory 'C:\Users\janja\Desktop\trigger-test\test-folder'. The directory name is invalid."
```
## Suggestion

I guess, we could validate the directory first before invoking it, if it was invalid, then we could disregard it or if we have a history of currently accessed (recently-valid) folders, maybe we could go back and CD'd to it and warn the user about the sudden jump of the directory.

If no history of accessed folders, then maybe just CD below the directory until we hit a valid directory.

## Demo

> **This was tested on Windows 11 with oh-my-posh version 11.3.0**

![WindowsTerminal_XrXNfa2Fm9](https://user-images.githubusercontent.com/5953927/193764926-f6f80521-32e5-49da-85a9-7a0e1421cd63.gif)

### Theme

https://github.com/CodexLink/chips.omp.json/blob/latest/chips.omp.json: the latest development version of https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/themes/chips.omp.json

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
<Cannot produce output from the `oh-my-posh` itself>
```

**Comment by JanDeDobbeleer** [comment]
@CodexLink this only works when 1 folder is deleted. As soon as you're in the scenario where multiple directories are gone, you can't get back easily anymore. That's because PowerShell can't handle that use-case itself with `Set-Location`. The only person who knows is you. The fact that you can't even run oh-my-posh straight from that location says enough about powerShell's inability to do anything even remotely sensible in this scenario. This error is a PowerShell error btw:

```
ResourceUnavailable: Program 'oh-my-posh' failed to run: An error occurred trying to start process '/Users/jan/homebrew/bin/oh-my-posh' with working directory '/Users/jan/test/hello/there'. No such file or directoryAt line:1 char:1
+ oh-my-posh debug
+ ~~~~~~~~~~~~~~~~.
```

EDIT: any other shell can handle this without issues.

**Comment by JanDeDobbeleer** [comment]
@CodexLink I have a proposal, we can fallback to the use HOME folder in this case and print that warning. That's the only sensible thing to do which leaves a working prompt.

**Comment by CodexLink** [comment]
> @CodexLink this only works when 1 folder is deleted. As soon as you're in the scenario where multiple directories are gone, you can't get back easily anymore. That's because PowerShell can't handle that use-case itself with `Set-Location`. The only person who knows is you. The fact that you can't even run oh-my-posh straight from that location says enough about powerShell's inability to do anything even remotely sensible in this scenario. This error is a PowerShell error btw:
> 
> ```
> ResourceUnavailable: Program 'oh-my-posh' failed to run: An error occurred trying to start process '/Users/jan/homebrew/bin/oh-my-posh' with working directory '/Users/jan/test/hello/there'. No such file or directoryAt line:1 char:1
> + oh-my-posh debug
> + ~~~~~~~~~~~~~~~~.
> ```
> 
> EDIT: any other shell can handle this without issues.

Oh, I see, so its the PowerShell's fault for being unable to return from previous valid folders whilst other shells can do it.

> @CodexLink I have a proposal, we can fallback to the use HOME folder in this case and print that warning. That's the only sensible thing to do which leaves a working prompt.

Yeah, I'm good with this @JanDeDobbeleer, I already thought about this one, but I did not sure why I attempted to propose the complex approach and forgot the simpler approach.
