### ISSUE TITLE
v12.31.0 broken on Linux

### ISSUE THREAD

**Issue by szymonos** [JanDeDobbeleer/oh-my-posh#3254]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

After installing v12.31.0 version oh-my-posh crashes with the message:
`fatal error: all goroutines are asleep - deadlock!`

Tested in WSL on Fedora and Debian distros, happens with bash and PowerShell shells.
Reverting to v12.30.1 solves the issue.

### Theme

robbyrussel, but happens on other themes too.

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

bash, PowerShell

### Log output

```Shell
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [semacquire]:
sync.runtime_SemacquireMutex(0x4?, 0x3?, 0x1?)
        /opt/hostedtoolcache/go/src/runtime/sema.go:77 +0x25
sync.(*Mutex).lockSlow(0x179e500)
        /opt/hostedtoolcache/go/src/sync/mutex.go:171 +0x165
sync.(*Mutex).Lock(...)
        /opt/hostedtoolcache/go/src/sync/mutex.go:90
sync.(*RWMutex).Lock(0x0?)
        /opt/hostedtoolcache/go/src/sync/rwmutex.go:147 +0x36
oh-my-posh/platform.(*Shell).Pwd(0xc000035080)
        /home/runner/work/oh-my-posh/oh-my-posh/src/platform/shell.go:334 +0xa5
oh-my-posh/platform.(*Shell).TemplateCache(0xc000035080)
        /home/runner/work/oh-my-posh/oh-my-posh/src/platform/shell.go:736 +0x35b
oh-my-posh/platform.(*Shell).Close(0xc000035080)
        /home/runner/work/oh-my-posh/oh-my-posh/src/platform/shell.go:684 +0x87
oh-my-posh/cli.runInit({0x7fff841ac940, 0x4})
        /home/runner/work/oh-my-posh/oh-my-posh/src/cli/init.go:79 +0x2a5
oh-my-posh/cli.glob..func12(0x1748900?, {0xc0cb18?, 0x5?, 0x5?})
        /home/runner/work/oh-my-posh/oh-my-posh/src/cli/root.go:28 +0xaa
github.com/spf13/cobra.(*Command).execute(0x1748900, {0xc0000341f0, 0x5, 0x5})
        /opt/hostedtoolcache/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x1748900)
        /opt/hostedtoolcache/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /opt/hostedtoolcache/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
oh-my-posh/cli.Execute({0xd52318?, 0xc0000061a0?})
        /home/runner/work/oh-my-posh/oh-my-posh/src/cli/root.go:41 +0x4a
main.main()
        /home/runner/work/oh-my-posh/oh-my-posh/src/main.go:10 +0x27
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [semacquire]:
sync.runtime_SemacquireMutex(0x4?, 0x2?, 0x3?)
        /opt/hostedtoolcache/go/src/runtime/sema.go:77 +0x25
sync.(*Mutex).lockSlow(0x179e500)
        /opt/hostedtoolcache/go/src/sync/mutex.go:171 +0x165
sync.(*Mutex).Lock(...)
        /opt/hostedtoolcache/go/src/sync/mutex.go:90
sync.(*RWMutex).Lock(0x0?)
        /opt/hostedtoolcache/go/src/sync/rwmutex.go:147 +0x36
oh-my-posh/platform.(*Shell).Pwd(0xc00019f020)
        /home/runner/work/oh-my-posh/oh-my-posh/src/platform/shell.go:334 +0xa5
oh-my-posh/platform.(*Shell).TemplateCache(0xc00019f020)
        /home/runner/work/oh-my-posh/oh-my-posh/src/platform/shell.go:736 +0x35b
oh-my-posh/platform.(*Shell).Close(0xc00019f020)
        /home/runner/work/oh-my-posh/oh-my-posh/src/platform/shell.go:684 +0x87
oh-my-posh/cli.runInit({0x7fff2e6c8938, 0x4})
        /home/runner/work/oh-my-posh/oh-my-posh/src/cli/init.go:75 +0x23e
oh-my-posh/cli.glob..func9(0x1747d80?, {0xc0002e30b0?, 0x1?, 0x3?})
        /home/runner/work/oh-my-posh/oh-my-posh/src/cli/init.go:38 +0x3b
github.com/spf13/cobra.(*Command).execute(0x1747d80, {0xc0002e3050, 0x3, 0x3})
        /opt/hostedtoolcache/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x1748900)
        /opt/hostedtoolcache/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /opt/hostedtoolcache/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
oh-my-posh/cli.Execute({0xd52318?, 0xc0000061a0?})
        /home/runner/work/oh-my-posh/oh-my-posh/src/cli/root.go:41 +0x4a
main.main()
        /home/runner/work/oh-my-posh/oh-my-posh/src/main.go:10 +0x27
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [semacquire]:
sync.runtime_SemacquireMutex(0x4?, 0x4?, 0x1?)
        /opt/hostedtoolcache/go/src/runtime/sema.go:77 +0x25
sync.(*Mutex).lockSlow(0x179e500)
        /opt/hostedtoolcache/go/src/sync/mutex.go:171 +0x165
sync.(*Mutex).Lock(...)
        /opt/hostedtoolcache/go/src/sync/mutex.go:90
sync.(*RWMutex).Lock(0x0?)
        /opt/hostedtoolcache/go/src/sync/rwmutex.go:147 +0x36
oh-my-posh/platform.(*Shell).Pwd(0xc000130fc0)
        /home/runner/work/oh-my-posh/oh-my-posh/src/platform/shell.go:334 +0xa5
oh-my-posh/platform.(*Shell).TemplateCache(0xc000130fc0)
        /home/runner/work/oh-my-posh/oh-my-posh/src/platform/shell.go:736 +0x35b
oh-my-posh/platform.(*Shell).Close(0xc000130fc0)
        /home/runner/work/oh-my-posh/oh-my-posh/src/platform/shell.go:684 +0x87
oh-my-posh/cli.glob..func10(0x1748620?, {0xc0002730b0, 0x1?, 0x3?})
        /home/runner/work/oh-my-posh/oh-my-posh/src/cli/print.go:84 +0x5a3
github.com/spf13/cobra.(*Command).execute(0x1748620, {0xc000273050, 0x3, 0x3})
        /opt/hostedtoolcache/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x1748900)
        /opt/hostedtoolcache/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /opt/hostedtoolcache/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
oh-my-posh/cli.Execute({0xd52318?, 0xc0000061a0?})
        /home/runner/work/oh-my-posh/oh-my-posh/src/cli/root.go:41 +0x4a
main.main()
        /home/runner/work/oh-my-posh/oh-my-posh/src/main.go:10 +0x27
```

**Comment by JanDeDobbeleer** [comment]
Argh. Thanks for letting me know. I'll revert that change. Should've seen this.

**Comment by JanDeDobbeleer** [comment]
Fix is building.
