### ISSUE TITLE
Concurrent read/write map issue

### ISSUE THREAD

**Issue by lnu** [JanDeDobbeleer/oh-my-posh#333]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

Since one of the refactoring(https://github.com/JanDeDobbeleer/oh-my-posh3/commit/c2bc901a414ac640e88a06ee2ddc0af7cc97a341) I'm getting randomly a concurrent read/write map error, which causes omp to crash with a fatal panic.

Map supports concurrent read but not writes. If a map is used concurrently, we should lock write access(like https://github.com/lnu/oh-my-posh3/blob/16c92aff2d38d25ac3c0cf79ef02b1e74e5c9092/src/regex.go)
I found it while testing languages. For this I put several files from different languages in the same folder.

### Environment

- Oh my Posh version: latest
- Theme: default
- Operating System: all
- Shell: all
- Terminal: all

### Steps to Reproduce

**Expected behavior:** [What you expected to happen]
No crash

**Actual behavior:** [What actually happened]
Random crash

**Comment by lnu** [comment]
<img width="1647" alt="Screenshot 2021-01-10 at 11 56 27" src="https://user-images.githubusercontent.com/1829553/104120931-f47d6800-533a-11eb-9e7d-3759fc1fc51a.png">

**Comment by tillig** [comment]
Unclear if it's related here, but I am on OMP 3.80.0 and get this:

```
fatal error: concurrent map read and map write
System.Management.Automation.RemoteException
goroutine 29 [running]:
runtime.throw(0x44a7454, 0x21)
	/Users/runner/hostedtoolcache/go/1.15.7/x64/src/runtime/panic.go:1116 +0x72 fp=0xc000065de8 sp=0xc000065db8 pc=0x4038112
runtime.mapaccess2_faststr(0x442e700, 0xc00010b530, 0x449bb34, 0x7, 0xc000065ea8, 0x4011238)
	/Users/runner/hostedtoolcache/go/1.15.7/x64/src/runtime/map_faststr.go:116 +0x4a5 fp=0xc000065e58 sp=0xc000065de8 pc=0x4017185
main.(*environment).runCommand(0xc0001185c0, 0x449bb34, 0x7, 0xc0000b0120, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0)
	/Users/runner/work/oh-my-posh3/oh-my-posh3/src/environment.go:168 +0x51 fp=0xc000065eb8 sp=0xc000065e58 pc=0x43bc3b1
main.(*kubectl).enabled(0xc0000ae0c0, 0x7ffeefbff976)
	/Users/runner/work/oh-my-posh3/oh-my-posh3/src/segment_kubectl.go:23 +0xdb fp=0xc000065f18 sp=0xc000065eb8 pc=0x43cbf3b
main.(*Segment).enabled(...)
	/Users/runner/work/oh-my-posh3/oh-my-posh3/src/segment.go:98
main.(*Segment).setStringValue(0xc00016a840, 0x4527c60, 0xc0001185c0, 0x7ffeefbff976, 0xd)
	/Users/runner/work/oh-my-posh3/oh-my-posh3/src/segment.go:178 +0x9c fp=0xc000065f68 sp=0xc000065f18 pc=0x43c205c
main.(*engine).setStringValues.func1(0xc0001271f4, 0xc000122a80, 0x7ffeefbff976, 0xd, 0xc00016a840)
	/Users/runner/work/oh-my-posh3/oh-my-posh3/src/engine.go:133 +0x85 fp=0xc000065fb8 sp=0xc000065f68 pc=0x43d5745
runtime.goexit()
	/Users/runner/hostedtoolcache/go/1.15.7/x64/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000065fc0 sp=0xc000065fb8 pc=0x406c7c1
created by main.(*engine).setStringValues
	/Users/runner/work/oh-my-posh3/oh-my-posh3/src/engine.go:131 +0xfa
System.Management.Automation.RemoteException
goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc0001271f4)
	/Users/runner/hostedtoolcache/go/1.15.7/x64/src/runtime/sema.go:56 +0x45
sync.(*WaitGroup).Wait(0xc0001271f4)
	/Users/runner/hostedtoolcache/go/1.15.7/x64/src/sync/waitgroup.go:130 +0x65
main.(*engine).setStringValues(0xc000122a80, 0xc00012c320, 0x9, 0x9)
	/Users/runner/work/oh-my-posh3/oh-my-posh3/src/engine.go:136 +0x12d
main.(*engine).renderBlockSegments(0xc000122a80, 0xc00012c2d0, 0x0, 0x0)
	/Users/runner/work/oh-my-posh3/oh-my-posh3/src/engine.go:108 +0x96
main.(*engine).render(0xc000122a80)
	/Users/runner/work/oh-my-posh3/oh-my-posh3/src/engine.go:155 +0xc5
main.main()
	/Users/runner/work/oh-my-posh3/oh-my-posh3/src/main.go:160 +0x7e8
System.Management.Automation.RemoteException
goroutine 28 [runnable]:
internal/poll.runtime_pollUnblock(0x4f85b18)
	/Users/runner/hostedtoolcache/go/1.15.7/x64/src/runtime/netpoll.go:326 +0x1ef
internal/poll.(*pollDesc).init(0xc0000201f8, 0xc0000201e0, 0x0, 0xc0000669e8)
	/Users/runner/hostedtoolcache/go/1.15.7/x64/src/internal/poll/fd_poll_runtime.go:42 +0xe5
internal/poll.(*FD).Init(0xc0000201e0, 0x449a127, 0x4, 0x1, 0xc000125200, 0x200000003)
	/Users/runner/hostedtoolcache/go/1.15.7/x64/src/internal/poll/fd_unix.go:62 +0x5f
os.newFile(0xc, 0x449c518, 0x9, 0x1, 0xc)
	/Users/runner/hostedtoolcache/go/1.15.7/x64/src/os/file_unix.go:155 +0x131
os.openFileNolog(0x449c518, 0x9, 0x0, 0x0, 0xc000066b60, 0x49b7328, 0x18)
	/Users/runner/hostedtoolcache/go/1.15.7/x64/src/os/file_unix.go:224 +0x1ce
os.OpenFile(0x449c518, 0x9, 0x0, 0x0, 0xc000066bd8, 0x401b725, 0x49b91f8)
	/Users/runner/hostedtoolcache/go/1.15.7/x64/src/os/file.go:327 +0x65
os.Open(...)
	/Users/runner/hostedtoolcache/go/1.15.7/x64/src/os/file.go:307
os/exec.(*Cmd).stdin(0xc000216000, 0x0, 0x3, 0xc00000e180)
	/Users/runner/hostedtoolcache/go/1.15.7/x64/src/os/exec/exec.go:246 +0x3ea
os/exec.(*Cmd).Start(0xc000216000, 0x4326201, 0xc00007e0f0)
	/Users/runner/hostedtoolcache/go/1.15.7/x64/src/os/exec/exec.go:407 +0x162
os/exec.(*Cmd).Run(0xc000216000, 0xc00007e0f0, 0x1)
	/Users/runner/hostedtoolcache/go/1.15.7/x64/src/os/exec/exec.go:338 +0x2b
os/exec.(*Cmd).Output(0xc000216000, 0x1e, 0xc000068020, 0x1, 0x1, 0xc000216000)
	/Users/runner/hostedtoolcache/go/1.15.7/x64/src/os/exec/exec.go:546 +0x92
main.(*environment).runCommand(0xc0001185c0, 0x449b1d9, 0x6, 0xc000068020, 0x1, 0x1, 0x6, 0x1, 0x449b1d9, 0xc000068010)
	/Users/runner/work/oh-my-posh3/oh-my-posh3/src/environment.go:171 +0xb7
main.(*language).setVersion(0xc000210000, 0xc00010bc01, 0x449eb9d)
	/Users/runner/work/oh-my-posh3/oh-my-posh3/src/segment_language.go:122 +0x95
main.(*language).string(0xc000210000, 0x47b7001, 0xc000066f08)
	/Users/runner/work/oh-my-posh3/oh-my-posh3/src/segment_language.go:73 +0x12c
main.(*dotnet).string(0xc000010018, 0x7ffeefbff901, 0xd)
	/Users/runner/work/oh-my-posh3/oh-my-posh3/src/segment_dotnet.go:14 +0x32
main.(*Segment).string(...)
	/Users/runner/work/oh-my-posh3/oh-my-posh3/src/segment.go:94
main.(*Segment).setStringValue(0xc00016a790, 0x4527c60, 0xc0001185c0, 0x7ffeefbff976, 0xd)
	/Users/runner/work/oh-my-posh3/oh-my-posh3/src/segment.go:179 +0xe7
main.(*engine).setStringValues.func1(0xc0001271f4, 0xc000122a80, 0x7ffeefbff976, 0xd, 0xc00016a790)
	/Users/runner/work/oh-my-posh3/oh-my-posh3/src/engine.go:133 +0x85
created by main.(*engine).setStringValues
	/Users/runner/work/oh-my-posh3/oh-my-posh3/src/engine.go:131 +0xfa
System.Management.Automation.RemoteException
goroutine 30 [runnable]:
strings.Index(0xc000022000, 0x38, 0x449968e, 0x1, 0x1e0)
	/Users/runner/hostedtoolcache/go/1.15.7/x64/src/strings/strings.go:1024 +0x6d8
os/exec.dedupEnvCase(0xc00013e900, 0xc00011c960, 0x1e, 0x1e, 0x0, 0x0, 0x203000)
	/Users/runner/hostedtoolcache/go/1.15.7/x64/src/os/exec/exec.go:751 +0x185
os/exec.dedupEnv(...)
	/Users/runner/hostedtoolcache/go/1.15.7/x64/src/os/exec/exec.go:742
os/exec.(*Cmd).Start(0xc00013e9a0, 0x4326201, 0xc00012c5a0)
	/Users/runner/hostedtoolcache/go/1.15.7/x64/src/os/exec/exec.go:425 +0x433
os/exec.(*Cmd).Run(0xc00013e9a0, 0xc00012c5a0, 0x4)
	/Users/runner/hostedtoolcache/go/1.15.7/x64/src/os/exec/exec.go:338 +0x2b
os/exec.(*Cmd).Output(0xc00013e9a0, 0x11, 0xc000144a00, 0x4, 0x4, 0xc00013e9a0)
	/Users/runner/hostedtoolcache/go/1.15.7/x64/src/os/exec/exec.go:546 +0x92
main.(*environment).runCommand(0xc0001185c0, 0x4499814, 0x2, 0xc000144a00, 0x4, 0x4, 0x47b7080, 0x0, 0x0, 0x0)
	/Users/runner/work/oh-my-posh3/oh-my-posh3/src/environment.go:171 +0xb7
main.(*az).enabled(0xc000144980, 0x7ffeefbff976)
	/Users/runner/work/oh-my-posh3/oh-my-posh3/src/segment_az.go:44 +0x134
main.(*Segment).enabled(...)
	/Users/runner/work/oh-my-posh3/oh-my-posh3/src/segment.go:98
main.(*Segment).setStringValue(0xc00016a8f0, 0x4527c60, 0xc0001185c0, 0x7ffeefbff976, 0xd)
	/Users/runner/work/oh-my-posh3/oh-my-posh3/src/segment.go:178 +0x9c
main.(*engine).setStringValues.func1(0xc0001271f4, 0xc000122a80, 0x7ffeefbff976, 0xd, 0xc00016a8f0)
	/Users/runner/work/oh-my-posh3/oh-my-posh3/src/engine.go:133 +0x85
created by main.(*engine).setStringValues
	/Users/runner/work/oh-my-posh3/oh-my-posh3/src/engine.go:131 +0xfa
```

It appears to be related to running multiple commands concurrently in the background. New issue? Same issue?

My config:

<details>
<summary>Expand this to see my config!</summary>
```json
{
  "blocks": [
    {
      "alignment": "left",
      "segments": [
        {
          "foreground": "#ff8080",
          "powerline_symbol": "\uE0B0",
          "properties": {
            "always_enabled": false,
            "display_exit_code": true,
            "error_color": "#e91e63",
            "postfix": "]",
            "prefix": "[⌧ "
          },
          "style": "powerline",
          "type": "exit"
        },
        {
          "background": "#ffe9aa",
          "foreground": "#100e23",
          "powerline_symbol": "\uE0B0",
          "properties": {
            "root_icon": "☠"
          },
          "style": "powerline",
          "type": "root"
        },
        {
          "background": "#1f1f1f",
          "foreground": "#ffffff",
          "powerline_symbol": "\uE0B0",
          "properties": {
            "postfix": " ",
            "user_info_separator": "@"
          },
          "style": "powerline",
          "type": "session"
        },
        {
          "background": "#0000c0",
          "foreground": "#ffffff",
          "powerline_symbol": "\uE0B0",
          "properties": {
            "prefix": "  ",
            "style": "short"
          },
          "style": "powerline",
          "type": "path"
        },
        {
          "background": "#0077c2",
          "foreground": "#ffffff",
          "powerline_symbol": "\uE0B0",
          "properties": {
            "prefix": "\uE705 ",
            "var_name": "LOCATION_STACK_DEPTH"
          },
          "style": "powerline",
          "type": "envvar"
        },
        {
          "background": "#00ffff",
          "foreground": "#000000",
          "powerline_symbol": "\uE0B0",
          "properties": {
            "display_mode": "always",
            "prefix": "  "
          },
          "style": "powerline",
          "type": "dotnet"
        },
        {
          "background": "#ebcc34",
          "foreground": "#000000",
          "powerline_symbol": "\uE0B0",
          "properties": {
            "prefix": " ⎈ "
          },
          "style": "powerline",
          "type": "kubectl"
        },
        {
          "background": "#3493eb",
          "foreground": "#000000",
          "powerline_symbol": "\uE0B0",
          "properties": {
            "prefix": " ﴃ "
          },
          "style": "powerline",
          "type": "az"
        },
        {
          "background": "#00cc00",
          "foreground": "#000000",
          "powerline_symbol": "\uE0B0",
          "properties": {
            "display_stash_count": true,
            "display_upstream_icon": true
          },
          "style": "powerline",
          "type": "git"
        }
      ],
      "type": "prompt",
      "vertical_offset": 0
    },
    {
      "alignment": "right",
      "segments": [
        {
          "foreground": "#ffffff",
          "properties": {
            "postfix": "]",
            "prefix": "[",
            "time_format": "15:04"
          },
          "style": "plain",
          "type": "time"
        }
      ],
      "type": "prompt",
      "vertical_offset": 0
    },
    {
      "type": "newline"
    },
    {
      "alignment": "left",
      "segments": [
        {
          "properties": {
            "postfix": ">"
          },
          "style": "plain",
          "type": "shell"
        }
      ],
      "type": "prompt",
      "vertical_offset": 0
    }
  ],
  "console_title": false,
  "final_space": true
}
```
</details>

**Comment by lnu** [comment]
Strange because we put a lock around the write and multiple reader without lock is supported. Maybe the logic of the lock is wrong? I also had the same issues when testing all languages at once, but with the lock it disappeared.

**Comment by JanDeDobbeleer** [comment]
@lnu I almost have a PR ready with a new atomic map. Needs validation on my end, will push asap.

**Comment by lnu** [comment]
Do you think we need to lock on read and write?

**Comment by JanDeDobbeleer** [comment]
@lnu yes we do. This is specifically on read it seems. PR incoming with a more powerful Map.
