### ISSUE TITLE
Multiple NameErrors 'get_command_context' in xonsh

### ISSUE THREAD

**Issue by AhmedAlomari** [JanDeDobbeleer/oh-my-posh#3532]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

upon enabling oh-my-posh in xonsh I get constant NameErrors, running WSL.

### Theme

Default theme.

### What OS are you seeing the problem on?

Windows, Linux

### Which shell are you using?

bash, other (please specify)

### Log output

```Shell
$ oh-my-posh debug                                                                                                    $

Version: 14.8.0

Segments:

ConsoleTitle(true) -   1 ms - xonsh in ahmed
session(true)      -   0 ms -  ahmed 
path(true)         -   4 ms -   ~
git(false)         -   0 ms -
root(false)        -   0 ms -
exit(true)         -   0 ms -  CONFIG ERROR 
node(false)        -   0 ms -
go(false)          -   0 ms -
python(false)      -   0 ms -
shell(true)        -   0 ms - in xonsh
time(true)         -   0 ms - at 16:10:40

Run duration: 13.1312ms

Cache path: /home/ahmed/.cache/oh-my-posh

Config path: /home/ahmed/$'/home/ahmed/$'/home/ahmed/$'/home/ahmed/'''''

Logs:

[DEBUG] 16:10:40.968 shell.go:Getenv:377 → NO DATA
[TRACE] 16:10:40.968 shell.go:Getenv(XDG_CACHE_HOME) - 30µs
[TRACE] 16:10:40.968 shell_unix.go:CachePath() - 78.1µs
[DEBUG] 16:10:40.973 shell.go:Getenv:377 → $'/home/ahmed/$'/home/ahmed/$'/home/ahmed/'''''
[TRACE] 16:10:40.973 shell.go:Getenv(POSH_THEME) - 13.2µs
[DEBUG] 16:10:40.973 shell_unix.go:Platform:63 → ubuntu
[TRACE] 16:10:40.973 shell.go:GOOS() - 900ns
[DEBUG] 16:10:40.973 shell.go:Pwd:405 → NO DATA
[TRACE] 16:10:40.973 shell.go:Pwd() - 42µs
[TRACE] 16:10:40.973 shell.go:resolveConfigPath() - 89.9µs
[TRACE] 16:10:40.973 shell.go:Init() - 5.1713ms
[TRACE] 16:10:40.973 shell.go:Flags() - 1.2µs
[ERROR] 16:10:40.973 config.go:loadConfig:131 → open /home/ahmed/$'/home/ahmed/$'/home/ahmed/$'/home/ahmed/''''': no such file or directory
[TRACE] 16:10:40.973 config.go:loadConfig() - 181.2µs
[TRACE] 16:10:40.973 shell.go:Flags() - 600ns
[DEBUG] 16:10:40.973 shell.go:Getenv:377 → NO DATA
[TRACE] 16:10:40.973 shell.go:Getenv(OMP_CACHE_DISABLED) - 5.9µs
[TRACE] 16:10:40.974 shell_unix.go:Root() - 1.5µs
[DEBUG] 16:10:40.974 shell.go:Shell:622 → process name: xonsh
[TRACE] 16:10:40.974 shell.go:Shell() - 691.2µs
[TRACE] 16:10:40.974 shell.go:ErrorCode() - 700ns
[DEBUG] 16:10:40.974 shell.go:Getenv:377 → Ubuntu-20.04
[TRACE] 16:10:40.974 shell.go:Getenv(WSL_DISTRO_NAME) - 4.9µs
[TRACE] 16:10:40.974 shell_unix.go:IsWsl() - 10.7µs
[DEBUG] 16:10:40.975 shell.go:Pwd:385 → /home/ahmed
[TRACE] 16:10:40.975 shell.go:Pwd() - 10.5µs
[TRACE] 16:10:40.975 shell.go:GOOS() - 600ns
[TRACE] 16:10:40.975 shell.go:GOOS() - 600ns
[TRACE] 16:10:40.975 shell.go:GOOS() - 600ns
[TRACE] 16:10:40.975 shell.go:GOOS() - 600ns
[TRACE] 16:10:40.975 shell.go:GOOS() - 600ns
[TRACE] 16:10:40.975 shell.go:GOOS() - 600ns
[TRACE] 16:10:40.975 shell.go:GOOS() - 700ns
[DEBUG] 16:10:40.975 shell.go:User:526 → ahmed
[TRACE] 16:10:40.975 shell.go:User() - 8.3µs
[DEBUG] 16:10:40.975 shell.go:Host:538 → DESKTOP-02BKQN8
[TRACE] 16:10:40.975 shell.go:Host() - 7.9µs
[TRACE] 16:10:40.975 shell.go:GOOS() - 700ns
[DEBUG] 16:10:40.975 shell_unix.go:Platform:63 → ubuntu
[TRACE] 16:10:40.975 shell.go:TemplateCache() - 857.5µs
[TRACE] 16:10:40.975 shell.go:Flags() - 600ns
[DEBUG] 16:10:40.975 shell.go:Pwd:385 → /home/ahmed
[TRACE] 16:10:40.975 shell.go:Pwd() - 4.8µs
[TRACE] 16:10:40.975 shell.go:GOOS() - 600ns
[DEBUG] 16:10:40.975 shell.go:Getenv:377 → NO DATA
[TRACE] 16:10:40.975 shell.go:Getenv(SSH_CONNECTION) - 17.3µs
[DEBUG] 16:10:40.975 shell.go:Getenv:377 → NO DATA
[TRACE] 16:10:40.975 shell.go:Getenv(SSH_CLIENT) - 4.3µs
[TRACE] 16:10:40.975 shell.go:TemplateCache() - 700ns
[TRACE] 16:10:40.975 shell.go:TemplateCache() - 800ns
[TRACE] 16:10:40.975 shell.go:Shell() - 700ns
[DEBUG] 16:10:40.975 shell.go:Pwd:385 → /home/ahmed
[TRACE] 16:10:40.975 shell.go:Pwd() - 5.7µs
[TRACE] 16:10:40.975 shell.go:GOOS() - 600ns
[DEBUG] 16:10:40.975 shell.go:Pwd:385 → /home/ahmed
[TRACE] 16:10:40.975 shell.go:Pwd() - 4.5µs
[TRACE] 16:10:40.975 shell.go:Shell() - 600ns
[TRACE] 16:10:40.975 shell.go:Shell() - 600ns
[TRACE] 16:10:40.975 shell.go:GOOS() - 900ns
[TRACE] 16:10:40.975 shell.go:PathSeparator() - 600ns
[TRACE] 16:10:40.975 shell.go:GOOS() - 700ns
[TRACE] 16:10:40.975 shell.go:GOOS() - 600ns
[TRACE] 16:10:40.975 shell.go:GOOS() - 600ns
[TRACE] 16:10:40.975 shell.go:GOOS() - 600ns
[TRACE] 16:10:40.975 shell.go:PathSeparator() - 600ns
[TRACE] 16:10:40.975 shell.go:PathSeparator() - 600ns
[TRACE] 16:10:40.975 shell.go:GOOS() - 600ns
[TRACE] 16:10:40.975 shell.go:GOOS() - 600ns
[TRACE] 16:10:40.975 shell.go:PathSeparator() - 600ns
[TRACE] 16:10:40.975 shell.go:GOOS() - 600ns
[TRACE] 16:10:40.975 shell.go:GOOS() - 600ns
[TRACE] 16:10:40.975 shell.go:PathSeparator() - 600ns
[TRACE] 16:10:40.975 shell.go:GOOS() - 600ns
[TRACE] 16:10:40.975 shell.go:GOOS() - 700ns
[TRACE] 16:10:40.975 shell.go:PathSeparator() - 600ns
[DEBUG] 16:10:40.975 shell.go:Pwd:385 → /home/ahmed
[TRACE] 16:10:40.975 shell.go:Pwd() - 4.9µs
[DEBUG] 16:10:40.975 shell.go:Getenv:377 → Ubuntu-20.04
[TRACE] 16:10:40.975 shell.go:Getenv(WSL_DISTRO_NAME) - 4.6µs
[TRACE] 16:10:40.975 shell_unix.go:IsWsl() - 10.2µs
[DEBUG] 16:10:40.979 shell.go:RunCommand:556 → //wsl.localhost/Ubuntu-20.04/home/ahmed
[TRACE] 16:10:40.979 shell.go:RunCommand(wslpath -m /home/ahmed) - 3.5329ms
[TRACE] 16:10:40.979 shell.go:StackCount() - 700ns
[TRACE] 16:10:40.979 shell_unix.go:DirIsWritable(/home/ahmed) - 6.7µs
[TRACE] 16:10:40.979 shell.go:TemplateCache() - 700ns
[TRACE] 16:10:40.979 shell.go:TemplateCache() - 600ns
[TRACE] 16:10:40.979 shell.go:Shell() - 900ns
[DEBUG] 16:10:40.979 shell.go:Pwd:385 → /home/ahmed
[TRACE] 16:10:40.979 shell.go:Pwd() - 5.6µs
[TRACE] 16:10:40.979 shell.go:GOOS() - 600ns
[DEBUG] 16:10:40.979 shell.go:Getenv:377 → Ubuntu-20.04
[TRACE] 16:10:40.979 shell.go:Getenv(WSL_DISTRO_NAME) - 4.6µs
[TRACE] 16:10:40.979 shell_unix.go:IsWsl() - 14µs
[DEBUG] 16:10:40.979 shell.go:FileContent:494 ↓
    4.4.0-19041-Microsoft

[TRACE] 16:10:40.979 shell.go:FileContent(/proc/sys/kernel/osrelease) - 36.7µs
[TRACE] 16:10:40.979 shell_unix.go:IsWsl2() - 67.5µs
[TRACE] 16:10:40.979 shell.go:GOOS() - 700ns
[DEBUG] 16:10:40.980 shell.go:CommandPath:577 → /usr/bin/git
[TRACE] 16:10:40.980 shell.go:CommandPath(git) - 187.7µs
[TRACE] 16:10:40.980 shell.go:HasCommand(git) - 204.6µs
[DEBUG] 16:10:40.980 shell.go:Pwd:385 → /home/ahmed
[TRACE] 16:10:40.980 shell.go:Pwd() - 4.9µs
[ERROR] 16:10:40.980 shell.go:HasParentFilePath:710 → stat /.git: no such file or directory
[TRACE] 16:10:40.980 shell.go:HasParentFilePath(.git) - 128.3µs
[DEBUG] 16:10:40.980 shell.go:Pwd:385 → /home/ahmed
[TRACE] 16:10:40.980 shell.go:Pwd() - 4.9µs
[TRACE] 16:10:40.980 shell.go:GOOS() - 600ns
[TRACE] 16:10:40.980 shell_unix.go:Root() - 1.2µs
[DEBUG] 16:10:40.980 shell.go:Pwd:385 → /home/ahmed
[TRACE] 16:10:40.980 shell.go:Pwd() - 4.8µs
[TRACE] 16:10:40.980 shell.go:GOOS() - 600ns
[TRACE] 16:10:40.980 shell.go:ErrorCode() - 600ns
[TRACE] 16:10:40.980 shell.go:TemplateCache() - 700ns
[TRACE] 16:10:40.980 shell.go:Shell() - 700ns
[TRACE] 16:10:40.980 shell.go:Flags() - 700ns
[DEBUG] 16:10:40.980 shell.go:Pwd:385 → /home/ahmed
[TRACE] 16:10:40.980 shell.go:Pwd() - 4.6µs
[TRACE] 16:10:40.980 shell.go:GOOS() - 700ns
[DEBUG] 16:10:40.980 shell.go:Pwd:385 → /home/ahmed
[TRACE] 16:10:40.980 shell.go:Pwd() - 4.6µs
[DEBUG] 16:10:40.980 shell.go:Pwd:385 → /home/ahmed
[TRACE] 16:10:40.980 shell.go:Pwd() - 4.4µs
[TRACE] 16:10:40.980 shell.go:GOOS() - 600ns
[DEBUG] 16:10:40.980 shell.go:Pwd:385 → /home/ahmed
[TRACE] 16:10:40.980 shell.go:Pwd() - 4.4µs
[DEBUG] 16:10:40.980 shell.go:Pwd:385 → /home/ahmed
[TRACE] 16:10:40.980 shell.go:Pwd() - 7.7µs
[TRACE] 16:10:40.980 shell.go:GOOS() - 600ns
[DEBUG] 16:10:40.980 shell.go:Pwd:385 → /home/ahmed
[TRACE] 16:10:40.980 shell.go:Pwd() - 4.4µs
[DEBUG] 16:10:40.980 shell.go:Pwd:385 → /home/ahmed
[TRACE] 16:10:40.980 shell.go:Pwd() - 4.3µs
[TRACE] 16:10:40.980 shell.go:GOOS() - 600ns
[TRACE] 16:10:40.980 shell.go:Shell() - 800ns
[TRACE] 16:10:40.980 shell.go:Flags() - 600ns
[TRACE] 16:10:40.980 shell.go:TemplateCache() - 700ns
[TRACE] 16:10:40.981 shell.go:TemplateCache() - 700ns
[TRACE] 16:10:40.981 shell.go:Shell() - 700ns
[DEBUG] 16:10:40.981 shell.go:Pwd:385 → /home/ahmed
[TRACE] 16:10:40.981 shell.go:Pwd() - 9.4µs
[TRACE] 16:10:40.981 shell.go:GOOS() - 700ns
[TRACE] 16:10:40.981 shell.go:TemplateCache() - 900ns
[TRACE] 16:10:40.981 shell.go:TemplateCache() - 800ns
[TRACE] 16:10:40.981 shell.go:Shell() - 600ns
[DEBUG] 16:10:40.981 shell.go:Getenv:377 → NO DATA
[TRACE] 16:10:40.981 shell.go:Getenv(XDG_CACHE_HOME) - 5.5µs
[TRACE] 16:10:40.981 shell_unix.go:CachePath() - 40.6µs
[TRACE] 16:10:40.981 shell.go:Flags() - 700ns
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/xonsh/prompt/__amalgam__.py", line 730, in __call__
    prompt = self._format_prompt(template=template)
  File "/usr/lib/python3/dist-packages/xonsh/prompt/__amalgam__.py", line 738, in _format_prompt
    template = template() if callable(template) else template
  File "<xonsh-code>", line 14, in posh_primary
NameError: name 'get_command_context' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/xonsh/prompt/__amalgam__.py", line 826, in _failover_template_format
    return template()
  File "<xonsh-code>", line 14, in posh_primary
NameError: name 'get_command_context' is not defined
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/xonsh/prompt/__amalgam__.py", line 730, in __call__
    prompt = self._format_prompt(template=template)
  File "/usr/lib/python3/dist-packages/xonsh/prompt/__amalgam__.py", line 738, in _format_prompt
    template = template() if callable(template) else template
  File "<xonsh-code>", line 18, in posh_right
NameError: name 'get_command_context' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/xonsh/prompt/__amalgam__.py", line 826, in _failover_template_format
    return template()
  File "<xonsh-code>", line 18, in posh_right
NameError: name 'get_command_context' is not defined
$
```

**Comment by JanDeDobbeleer** [comment]
@AhmedAlomari are you on the latest xonsh (0.13.4)? I validated this on macOS with the latest available xonsh and this worked, I can even see the command as correctly defined.

**Comment by AhmedAlomari** [comment]
Whoops my bad @JanDeDobbeleer , turns out the ubuntu package for 20.04 is terribly out of date. I'll reopen if the issue persists on the latest version.
