### ISSUE TITLE
Test failure in TestStringImageFileWithText since 16.1.0

### ISSUE THREAD

**Issue by arjan-s** [JanDeDobbeleer/oh-my-posh#3860]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Ever since version 16.1.0, at least one test fails on NixOS when building the package from source. This could obviously be an error caused by the way NixOS does things, but since I can't figure it out myself I'm posting the stack trace here. Hope you can help solve this!

### Theme

n/a

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

bash

### Log output

```Shell
running tests
ok      github.com/jandedobbeleer/oh-my-posh/src        0.004s [no tests to run]
ok      github.com/jandedobbeleer/oh-my-posh/src/ansi   0.003s
--- FAIL: TestStringImageFileWithText (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xb3369d]

goroutine 9 [running]:
testing.tRunner.func1.2({0xc2e3a0, 0x13505d0})
        /nix/store/8v5zwymidmry0wd3lhj6zggskzsvqrfk-go-1.20.4/share/go/src/testing/testing.go:1526 +0x24e
testing.tRunner.func1()
        /nix/store/8v5zwymidmry0wd3lhj6zggskzsvqrfk-go-1.20.4/share/go/src/testing/testing.go:1529 +0x39f
panic({0xc2e3a0, 0x13505d0})
        /nix/store/8v5zwymidmry0wd3lhj6zggskzsvqrfk-go-1.20.4/share/go/src/runtime/panic.go:884 +0x213
golang.org/x/image/font.MeasureString({0x0, 0x0}, {0xc00052c5a0, 0xc})
        /build/source/src/vendor/golang.org/x/image/font/font.go:288 +0x3d
golang.org/x/image/font.(*Drawer).MeasureString(...)
        /build/source/src/vendor/golang.org/x/image/font/font.go:216
github.com/jandedobbeleer/oh-my-posh/src/engine.(*ImageRenderer).measureContent(0xc0004f9d80)
        /build/source/src/engine/image.go:398 +0xb8
github.com/jandedobbeleer/oh-my-posh/src/engine.(*ImageRenderer).SavePNG(0xc0004f9d80)
        /build/source/src/engine/image.go:414 +0x46
github.com/jandedobbeleer/oh-my-posh/src/engine.runImageTest({0xcfee3a, 0x19}, {0xceaa88, 0x6})
        /build/source/src/engine/image_test.go:52 +0x1d3
github.com/jandedobbeleer/oh-my-posh/src/engine.TestStringImageFileWithText(0x0?)
        /build/source/src/engine/image_test.go:61 +0x7f
testing.tRunner(0xc0003e6340, 0xd47c78)
        /nix/store/8v5zwymidmry0wd3lhj6zggskzsvqrfk-go-1.20.4/share/go/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
        /nix/store/8v5zwymidmry0wd3lhj6zggskzsvqrfk-go-1.20.4/share/go/src/testing/testing.go:1629 +0x3ea
FAIL    github.com/jandedobbeleer/oh-my-posh/src/engine 0.010s
FAIL
```

**Comment by JanDeDobbeleer** [comment]
I'm pretty sure the font download fails which makes everything else downstream fail as well. I tried in the past to work with nixos but it was so painful I stopped looking into it. I'll try to adjust the test so that font download failures no longer fail the test. If you could validate that would be ace.

**Comment by arjan-s** [comment]
Ahh, that makes sense, thanks!
The builds on NixOS are sandboxed without internet access, that's why it's failing.
No need to adjust the test, we'll just skip it due to requiring internet access.

**Comment by JanDeDobbeleer** [comment]
@arjan-s still, it shouldn't simply fail. The test can't execute in this case and it should succeed with a warning. I'll adjust that.
