### ISSUE TITLE
Unable to build on nixOS suddenly and confusingly

### ISSUE THREAD

**Issue by BirdeeHub** [JanDeDobbeleer/oh-my-posh#4622]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Updating broke this test on nixOS flake update. For some reason, it only broke today, but I cant get it to work unless I go all the way back to nixpkgs commit 
```
    nixpkgs_older.url = "github:nixos/nixpkgs/6660475dea29309327ee3b2e6824ec0011589017";
```
Im using this nixpkgs commit to pin oh-my-posh to the previous version. I am unsure why it only broke today and yet I had to go back 2 months to find a working version.

This is the error:
```
building the system configuration...
warning: Git tree '/home/birdee/Projects/birdeeSystems' is dirty
error: builder for '/nix/store/nsjl71djh4crgbf4lx91dy2d9mwdd16f-oh-my-posh-18.26.1.drv' failed with exit code 1;
       last 10 log lines:
       > github.com/jandedobbeleer/oh-my-posh/src/segments.(*Nba).Enabled(0xc00030fef0)
       >     /build/source/src/segments/nba.go:143 +0x1c
       > github.com/jandedobbeleer/oh-my-posh/src/segments.TestNBASegment(0xc0004836c0?)
       >   /build/source/src/segments/nba_test.go:114 +0xaf3
       > testing.tRunner(0xc0004836c0, 0xb6e0e0)
       >     /nix/store/rccpgf2bnh58hhh4908p78i1rln9gzvp-go-1.21.5/share/go/src/testing/testing.go:1595 +0xff
       > created by testing.(*T).Run in goroutine 1
       >   /nix/store/rccpgf2bnh58hhh4908p78i1rln9gzvp-go-1.21.5/share/go/src/testing/testing.go:1648 +0x3ad
       > FAIL github.com/jandedobbeleer/oh-my-posh/src/segments       0.507s
       > FAIL
       For full logs, run 'nix log /nix/store/nsjl71djh4crgbf4lx91dy2d9mwdd16f-oh-my-posh-18.26.1.drv'.
error: 1 dependencies of derivation '/nix/store/m4ai9g4h4g99pz4kfmrj8x9bln0v1ac6-system-path.drv' failed to build
error (ignored): error: cannot unlink '/tmp/nix-build-virtualbox-7.0.12.drv-2/VirtualBox-7.0.12': Directory not empty
error: 1 dependencies of derivation '/nix/store/6armjaaz1galavpz6g71yr7cqzjrbpih-nixos-system-nestOS-24.05.20240113.9b19f5e.drv' failed to build
```

### Theme

https://github.com/BirdeeHub/birdeeSystems/blob/main/common/shell/atomic-emodipt.omp.json

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

zsh

### Log output

```Shell
I cant get it to install due to failed tests. Here is the log for the derivation build, the output of the command suggested in the error above.
nix log /nix/store/nsjl71djh4crgbf4lx91dy2d9mwdd16f-oh-my-posh-18.26.1.drv

@nix { "action": "setPhase", "phase": "unpackPhase" }
Running phase: unpackPhase
unpacking source archive /nix/store/9r20wj4y7yarwb0a3ar6bya1w5afbm2z-source
source root is source/src
@nix { "action": "setPhase", "phase": "patchPhase" }
Running phase: patchPhase
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
Running phase: configurePhase
@nix { "action": "setPhase", "phase": "buildPhase" }
Running phase: buildPhase
Building subPackage .
Building subPackage ./ansi
Building subPackage ./build
Building subPackage ./cli
Building subPackage ./constants
Building subPackage ./engine
Building subPackage ./font
Building subPackage ./http
Building subPackage ./log
Building subPackage ./mock
Building subPackage ./platform
Building subPackage ./platform/battery
Building subPackage ./platform/cmd
Building subPackage ./properties
Building subPackage ./regex
Building subPackage ./segments
Building subPackage ./shell
Building subPackage ./template
Building subPackage ./upgrade
buildPhase completed in 37 seconds
@nix { "action": "setPhase", "phase": "checkPhase" }
Running phase: checkPhase
ok  	github.com/jandedobbeleer/oh-my-posh/src	0.005s [no tests to run]
ok  	github.com/jandedobbeleer/oh-my-posh/src/ansi	0.006s
ok  	github.com/jandedobbeleer/oh-my-posh/src/engine	0.019s
ok  	github.com/jandedobbeleer/oh-my-posh/src/http	0.008s
ok  	github.com/jandedobbeleer/oh-my-posh/src/platform	0.003s
ok  	github.com/jandedobbeleer/oh-my-posh/src/platform/battery	0.002s
ok  	github.com/jandedobbeleer/oh-my-posh/src/properties	0.004s
--- FAIL: TestNBASegment (0.00s)
panic: 

mock: Unexpected Method Call
-----------------------------

HTTPRequest(string)
		0: "https://stats.nba.com/stats/internationalbroadcasterschedule?LeagueID=00&Season=2023&Date=01/14/2024&RegionID=1&EST=Y"

The closest call I have is: 

HTTPRequest(string)
		0: "https://cdn.nba.com/static/json/liveData/scoreboard/todaysScoreboard_00.json"


Diff: 0: FAIL:  (string=https://stats.nba.com/stats/internationalbroadcasterschedule?LeagueID=00&Season=2023&Date=01/14/2024&RegionID=1&EST=Y) != (string=https://cdn.nba.com/static/json/liveData/scoreboard/todaysScoreboard_00.json) [recovered]
	panic: 

mock: Unexpected Method Call
-----------------------------

HTTPRequest(string)
		0: "https://stats.nba.com/stats/internationalbroadcasterschedule?LeagueID=00&Season=2023&Date=01/14/2024&RegionID=1&EST=Y"

The closest call I have is: 

HTTPRequest(string)
		0: "https://cdn.nba.com/static/json/liveData/scoreboard/todaysScoreboard_00.json"


Diff: 0: FAIL:  (string=https://stats.nba.com/stats/internationalbroadcasterschedule?LeagueID=00&Season=2023&Date=01/14/2024&RegionID=1&EST=Y) != (string=https://cdn.nba.com/static/json/liveData/scoreboard/todaysScoreboard_00.json)

goroutine 112 [running]:
testing.tRunner.func1.2({0xa44e20, 0xc00024cd90})
	/nix/store/rccpgf2bnh58hhh4908p78i1rln9gzvp-go-1.21.5/share/go/src/testing/testing.go:1545 +0x238
testing.tRunner.func1()
	/nix/store/rccpgf2bnh58hhh4908p78i1rln9gzvp-go-1.21.5/share/go/src/testing/testing.go:1548 +0x397
panic({0xa44e20?, 0xc00024cd90?})
	/nix/store/rccpgf2bnh58hhh4908p78i1rln9gzvp-go-1.21.5/share/go/src/runtime/panic.go:914 +0x21f
github.com/stretchr/testify/mock.(*Mock).fail(0xc0002ecaf0, {0xb4915b?, 0xc00024c0f0?}, {0xc00039ef40?, 0x1?, 0x1?})
	/build/source/src/vendor/github.com/stretchr/testify/mock/mock.go:332 +0x134
github.com/stretchr/testify/mock.(*Mock).MethodCalled(0xc0002ecaf0, {0xce2fe8, 0xb}, {0xc00024c850?, 0x1, 0x1})
	/build/source/src/vendor/github.com/stretchr/testify/mock/mock.go:492 +0x55d
github.com/stretchr/testify/mock.(*Mock).Called(0xc000030c00?, {0xc00024c850, 0x1, 0x1})
	/build/source/src/vendor/github.com/stretchr/testify/mock/mock.go:464 +0x137
github.com/jandedobbeleer/oh-my-posh/src/mock.(*MockedEnvironment).HTTPRequest(0xc0002ecaf0, {0xc000030c00, 0x75}, {0xb45c75?, 0x3?}, 0xb0fa15?, {0x7fffb14268b8?, 0xb10be5?, 0x10?})
	/build/source/src/mock/environment.go:149 +0x8d
github.com/jandedobbeleer/oh-my-posh/src/segments.(*Nba).retrieveScheduleData(0xc0001222c0, {0xc000494868, 0x3}, 0x1?)
	/build/source/src/segments/nba.go:252 +0x363
github.com/jandedobbeleer/oh-my-posh/src/segments.(*Nba).getAvailableGameData(0xc0002ecaf0?, {0xc000494868, 0x3}, 0xc000494868?)
	/build/source/src/segments/nba.go:301 +0x45
github.com/jandedobbeleer/oh-my-posh/src/segments.(*Nba).getResult(0xc0001222c0)
	/build/source/src/segments/nba.go:385 +0x312
github.com/jandedobbeleer/oh-my-posh/src/segments.(*Nba).Enabled(0xc0001222c0)
	/build/source/src/segments/nba.go:143 +0x1c
github.com/jandedobbeleer/oh-my-posh/src/segments.TestNBASegment(0xc000482d00?)
	/build/source/src/segments/nba_test.go:114 +0xaf3
testing.tRunner(0xc000482d00, 0xb6e0e0)
	/nix/store/rccpgf2bnh58hhh4908p78i1rln9gzvp-go-1.21.5/share/go/src/testing/testing.go:1595 +0xff
created by testing.(*T).Run in goroutine 1
	/nix/store/rccpgf2bnh58hhh4908p78i1rln9gzvp-go-1.21.5/share/go/src/testing/testing.go:1648 +0x3ad
FAIL	github.com/jandedobbeleer/oh-my-posh/src/segments	0.133s
FAIL
```

**Comment by JanDeDobbeleer** [comment]
@BirdeeHub I don't maintain the nix build. Seems like it's outdated as that was an issue with the test not handling year changes. Fixed that earlier this month.

**Comment by JanDeDobbeleer** [comment]
@BirdeeHub the logs say `oh-my-posh-18.26.1` so you'll need to ask the maintainer (don't know who that is) to update to the latest version.

**Comment by BirdeeHub** [comment]
hmm ok. I dont know who that is either but I might just go ahead and try it myself. Maybe I can just update the hash
