### ISSUE TITLE
Cannot activate Conda environment in Git Bash

### ISSUE THREAD

**Issue by pyxelr** [JanDeDobbeleer/oh-my-posh#939]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I am using Oh My Posh on the latest Windows 10 Pro through scoop, and I am experiencing absolutely no issues with using my theme through PowerShell.

In the beginning, I wanted to point out that [https://ohmyposh.dev/docs/windows](https://ohmyposh.dev/docs/windows) advises setting Git Bash configuration to `~/.bashrc`, whereas on Windows it should be actually saved in: `~/.bash_profile`.

After applying the following line to `~/.bash_profile`:
```
eval "$(oh-my-posh --init --shell bash --config ~/.mytheme.omp.json)"
```
I have noticed two problems:
1) In VS Code, the 1st line of my theme is sometimes preceded with `\` character for the first 2-3 commands. Afterwards, it's gone. However, if I execute `clear`, it comes back for another 2-3 commands.
2) The major problem is that when I execute `conda activate base` (or activate any other conda environment), I am getting the error attached in the log section of this report. This error happens no matter which software will be used to execute Git Bash commands.

### Version

3.180.0

### Theme

Modified `stelbent.minimal` (with displayed Python venv on the right side):
[mytheme.omp.json.zip](https://github.com/JanDeDobbeleer/oh-my-posh/files/7112332/mytheme.omp.json.zip)

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

bash

### Relevant log output

```shell
The error message after running `conda activate zzz`. I've hidden my env variables with `(...)`:


$ conda activate zzz

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\Pawel\miniconda3\lib\site-packages\conda\cli\main.py", line 140, in main
        return activator_main()
      File "C:\Users\Pawel\miniconda3\lib\site-packages\conda\activate.py", line 1210, in main
        print(activator.execute(), end='')
      File "C:\Users\Pawel\miniconda3\lib\encodings\cp1250.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\u250c' in position 36: character maps to <undefined>

`$ C:\Users\Pawel\miniconda3\Scripts\conda-script.py shell.posix activate zzz`

  environment variables:
  (...)

     active environment : base
    active env location : C:\Users\Pawel\miniconda3
            shell level : 1
       user config file : C:\Users\Pawel\.condarc
 populated config files : C:\Users\Pawel\.condarc
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.9.6.final.0
       virtual packages : __cuda=10.1=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\Pawel\miniconda3  (writable)
      conda av data dir : C:\Users\Pawel\miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\Pawel\miniconda3\pkgs
                          C:\Users\Pawel\.conda\pkgs
                          C:\Users\Pawel\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Pawel\miniconda3\envs
                          C:\Users\Pawel\.conda\envs
                          C:\Users\Pawel\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.9.6 Windows/10 Windows/10.0.19043
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
```
```

**Comment by JanDeDobbeleer** [comment]
1. Never seen before. Most likely that's something on the system or your theme.
2. That's a bug in conda more than anything else. It probably can't handle UTF8 for some reason (is that in bash or Powershell?)

**Comment by pyxelr** [comment]
1. Indeed, it only happens inside of VS Code's Git Bash terminal. I noticed that this `\` character disappears either after some commands are executed, or as soon as I simply resize the terminal window or even move the whole VS Code window. I will try to find out the solution on my own, but here is how it looks:
![2021-09-06_09-37-10](https://user-images.githubusercontent.com/30161753/132178470-304e7d4d-1b77-409f-95e4-c05fa825a5de.png)

2. With PowerShell, I can activate conda environments without any issues. This conda bug happens for Git Bash only, no matter if I use Git Bash inside of VS Code, Windows Terminal, ConEmu or Git Bash app itself. I also verified that it occurs for any Oh My Posh theme (not just my custom one), and it happens on every of my Windows machine (3 of them).

Here is how my `~/.bash_profile` looks like:
```
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
eval "$('/c/Users/pawel/Miniconda3/Scripts/conda.exe' 'shell.bash' 'hook')"
# <<< conda initialize <<<

eval "$(oh-my-posh --init --shell bash --config ~/.mytheme.omp.json)"
```
The first 4 lines are added when I execute `conda init bash` inside of Git Bash, which is obligatory. If I remove these lines, I can execute `conda activate base`, but the environment will not be activated since I am missing the init configuration.

**Comment by JanDeDobbeleer** [comment]
@pyxelr for 2, there seems to be a way to [set Python to UTF8](https://github.com/conda/conda/issues/7445#issuecomment-774579800) for related issues.

**Comment by pyxelr** [comment]
@JanDeDobbeleer: Thank you!
The problem number 2 was solved by setting the suggested environment variables as user variables: `PYTHONIOENCODING` and `PYTHONLEGACYWINDOWSSTDIO` to `UTF-8`.

Later, I will continue my research on issue number 1.

As mentioned in the beginning, you may consider updating the docs to mention the right .bashrc file on Windows.

**Comment by pyxelr** [comment]
@JanDeDobbeleer: For issue number 1, I compared my theme to [jandedobbeleer.omp.json](https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/themes/jandedobbeleer.omp.json), which had no issues. From there, I knew that there is nothing wrong with VS Code.

To resolve this problem, I had to modify the value of `"osc99"` from `true` to `false`.
Could you let me know if setting it to false may bring any consequences?

**Comment by JanDeDobbeleer** [comment]
@pyxelr no, it only alerts the terminal of the current folder. And that might be the issue. Path separators might not be escaped properly.

**Comment by pyxelr** [comment]
@JanDeDobbeleer: Once again, thank you for such an immediate help! From my side, I consider this discussion to be closed.

**Comment by JanDeDobbeleer** [comment]
Take it easy bot, I need to still do some doc changes.

**Comment by coding-famer** [comment]
> 

sorry but could you tell me that how can I set PYTHONIOENCODING and PYTHONLEGACYWINDOWSSTDIO to UTF-8.

**Comment by coding-famer** [comment]
> @JanDeDobbeleer: Thank you! The problem number 2 was solved by setting the suggested environment variables as user variables: `PYTHONIOENCODING` and `PYTHONLEGACYWINDOWSSTDIO` to `UTF-8`.
> 
> Later, I will continue my research on issue number 1.
> 
> As mentioned in the beginning, you may consider updating the docs to mention the right .bashrc file on Windows.

sorry but may I know how can I set PYTHONIOENCODING and PYTHONLEGACYWINDOWSSTDIO to UTF-8?

**Comment by lrfreeman** [comment]
I am having the same issue but with git bash in the windows terminal. Adding:

`eval "$(oh-my-posh init bash)` to my ~/.bash_profile prevents me from opening any conda environments. Removing the bash line then allows the conda environments to run again. Here is the error I get when running a conda environment: 

```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\laurence\miniconda3\lib\site-packages\conda\exceptions.py", line 1129, in __call__
        return func(*args, **kwargs)
      File "C:\Users\laurence\miniconda3\lib\site-packages\conda\cli\main.py", line 111, in main_sourced
        print(activator.execute(), end="")
      File "C:\Users\laurence\miniconda3\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\ue0b6' in position 37: character maps to <undefined>

`$ C:\Users\laurence\miniconda3\Scripts\conda-script.py shell.posix activate subgoal`

  environment variables:
             ACLOCAL_PATH=C:\Program Files\Git\mingw64\share\aclocal;C:\Program
                          Files\Git\usr\share\aclocal
             AMDRMSDKPATH=C:\Program Files\AMD\RyzenMasterSDK\
                 CIO_TEST=<not set>
                CONDA_EXE=C:/Users/laurence/miniconda3\Scripts\conda.exe
    CONDA_PROMPT_MODIFIER=false
         CONDA_PYTHON_EXE=C:/Users/laurence/miniconda3\python.exe
               CONDA_ROOT=C:\Users\laurence\miniconda3
              CONDA_SHLVL=0
           CURL_CA_BUNDLE=<not set>
                  EXEPATH=C:\Program Files\Git\bin
                 HOMEPATH=\Users\laurence
                 INFOPATH=C:\Program Files\Git\usr\local\info;C:\Program
                          Files\Git\usr\share\info;C:\Program Files\Git\usr\info;C:\Program
                          Files\Git\share\info
                  MANPATH=C:\Program Files\Git\mingw64\local\man;C:\Program
                          Files\Git\mingw64\share\man;C:\Program
                          Files\Git\usr\local\man;C:\Program Files\Git\usr\share\man;C:\Program
                          Files\Git\usr\man;C:\Program Files\Git\share\man
            ORIGINAL_PATH=C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users
                          \laurence\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;
                          C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH
                          ;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program
                          Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program
                          Files\Git\cmd;C:\Program Files\GitHub CLI;C:\Users\laurence\miniconda3
                          ;C:\Users\laurence\miniconda3\Library\mingw-w64\bin;C:\Users\laurence\
                          miniconda3\Library\usr\bin;C:\Users\laurence\miniconda3\Library\bin;C:
                          \Users\laurence\miniconda3\Scripts;C:\Users\laurence\AppData\Local\Mic
                          rosoft\WindowsApps;C:\Users\laurence\AppData\Local\Programs\Microsoft
                          VS Code\bin;C:\Users\laurence\AppData\Local\Programs\oh-my-posh\bin
                     PATH=C;C:\Program Files\Git\Users\laurence\miniconda3\condabin;C:\Users\lau
                          rence\bin;C:\Program Files\Git\mingw64\bin;C:\Program
                          Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program
                          Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Gi
                          t\usr\bin;C:\Users\laurence\bin;C:\Windows\system32;C:\Windows;C:\Wind
                          ows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Window
                          s\System32\OpenSSH;C:\Program Files (x86)\NVIDIA
                          Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA
                          NvDLISR;C:\Program Files\Git\cmd;C:\Program Files\GitHub CLI;C:\Users\
                          laurence\miniconda3;C:\Users\laurence\miniconda3\Library\mingw-w64\bin
                          ;C:\Users\laurence\miniconda3\Library\usr\bin;C:\Users\laurence\minico
                          nda3\Library\bin;C:\Users\laurence\miniconda3\Scripts;C:\Users\laurenc
                          e\AppData\Local\Microsoft\WindowsApps;C:\Users\laurence\AppData\Local\
                          Programs\Microsoft VS
                          Code\bin;C:\Users\laurence\AppData\Local\Programs\oh-my-
                          posh\bin;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program
                          Files\Git\usr\bin\core_perl
          PKG_CONFIG_PATH=C:\Program Files\Git\mingw64\lib\pkgconfig;C:\Program
                          Files\Git\mingw64\share\pkgconfig
         POSH_THEMES_PATH=C:\Users\laurence\AppData\Local\Programs\oh-my-posh\themes
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
            shell level : 0
       user config file : C:\Users\laurence\.condarc
 populated config files :
          conda version : 22.9.0
    conda-build version : not installed
         python version : 3.9.12.final.0
       virtual packages : __cuda=11.7=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\laurence\miniconda3  (writable)
      conda av data dir : C:\Users\laurence\miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\laurence\miniconda3\pkgs
                          C:\Users\laurence\.conda\pkgs
                          C:\Users\laurence\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\laurence\miniconda3\envs
                          C:\Users\laurence\.conda\envs
                          C:\Users\laurence\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/22.9.0 requests/2.28.1 CPython/3.9.12 Windows/10 Windows/10.0.19044
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

**Comment by JanDeDobbeleer** [comment]
@3man1992 that's a Conda bug as it can't handle UTF8. See [here](https://stackoverflow.com/questions/69130762/anaconda-prompt-fail-to-launch-unicodeencodeerror-utf-8-codec-cant-encode-c) for a possible solution.

**Comment by lrfreeman** [comment]
Thanks @JanDeDobbeleer.

I fixed it by adding an alias to my ~/.bash_profile
`alias posh="PYTHONUTF8=1"`
So now I run:
`posh source activate environment_name`
In gitbash and the conda environment activates. This was the only variant that worked for me.
